const fs=require('fs'),path=require('path'),http=require('http');
const {chromium}=require('C:/Users/Pollard_R/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root=path.resolve(__dirname,'../..'),site='C:/Users/Pollard_R/AppData/Local/Temp/LatinJosephus-Whiston-Index-disposable-20261009';
const expected=JSON.parse(fs.readFileSync(path.join(__dirname,'CONTENTS_EXPECTATIONS.json'),'utf8')),existing=JSON.parse(fs.readFileSync(path.join(__dirname,'EXISTING_CONTENTS_EXPECTATIONS.json'),'utf8'));
const renderer=fs.readFileSync(path.join(site,'assets/js/renderTei.js'),'utf8');
const report={result:'RUNNING',site,checks:[],interactions:[],existing:[],screenshots:[],pageErrors:[],failedRequests:[]};
const save=()=>fs.writeFileSync(path.join(__dirname,'BROWSER_QA.json'),JSON.stringify(report,null,2));
const server=http.createServer((req,res)=>{const u=new URL(req.url,'http://localhost');let target=path.resolve(site,'.'+decodeURIComponent(u.pathname));if(!target.startsWith(site.replaceAll('/',path.sep)+path.sep)){res.statusCode=403;res.end();return;}if(fs.existsSync(target)&&fs.statSync(target).isDirectory())target=path.join(target,'index.html');if(!fs.existsSync(target)){res.statusCode=404;res.end();return;}res.setHeader('Content-Type',({'.html':'text/html','.xml':'application/xml','.js':'text/javascript','.css':'text/css','.otf':'font/otf','.woff2':'font/woff2','.svg':'image/svg+xml','.png':'image/png'})[path.extname(target)]||'application/octet-stream');res.end(fs.readFileSync(target));});
(async()=>{
 await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin=`http://127.0.0.1:${server.address().port}`;const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'});const context=await browser.newContext({viewport:{width:1690,height:1100},deviceScaleFactor:1});
 await context.route('**/assets/js/renderTei.js',route=>route.fulfill({contentType:'text/javascript',body:renderer.replace('  bookTitle.innerText = activeWork.title;','  window.__toc={state:()=>({...state}),reload,assign:p=>Object.assign(state,p)};\n  bookTitle.innerText = activeWork.title;').replaceAll('setState(() => {','window.__tocPending = setState(() => {').replace('  reload().then(() => {','  reload().then(() => {\n    window.__tocReady=true;')}));
 const page=await context.newPage();page.on('pageerror',e=>report.pageErrors.push(String(e)));page.on('requestfailed',r=>report.failedRequests.push({url:r.url(),error:r.failure()?.errorText}));
 async function open(route){await page.goto(origin+route,{waitUntil:'load',timeout:60000});await page.waitForFunction(()=>window.__tocReady,{},{timeout:60000});await page.evaluate(()=>document.fonts.ready);}
 async function settle(){await page.evaluate(()=>window.__tocPending);}
 async function snap(name){await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:path.join(__dirname,name)});report.screenshots.push(name);}
 const before=fs.readFileSync(path.join(__dirname,'registry-before.xml'));await context.route('**/assets/xml/source-contents.xml*',route=>route.fulfill({contentType:'application/xml',body:before}));
 for(const theme of ['light','dark'])for(const book of [3,5,14]){await open(`/antiquities/?book=${book}&view=contents`);await page.evaluate(t=>document.documentElement.dataset.theme=t,theme);if(await page.locator("#english .source-contents").textContent()!=="No source table of contents is available for this witness.")throw Error("Before registry interception failed");await snap(`BEFORE_Whiston-${book}_${theme}.png`);}
 await context.unroute('**/assets/xml/source-contents.xml*');
 for(const theme of ['light','dark'])for(const e of expected){
  await open(`/antiquities/?book=${e.book}&view=contents&extra=keep#retained`);await page.evaluate(t=>document.documentElement.dataset.theme=t,theme);
  const data=await page.evaluate(e=>{
   const n=document.querySelector('#english .source-contents');if(!n)throw Error('English contents absent');const q=window.__toc.state();if(q.viewingLevel!=='contents-level')throw Error('Wrong view');
   const opts=[...document.querySelector('#chapter-selector').options];if(opts[0].value!=='contents')throw Error('TOC not first');
   const roots=[...n.children].filter(x=>x.localName.startsWith('tei-'));if(JSON.stringify(roots.map(x=>x.textContent))!==JSON.stringify(e.texts))throw Error('Complete body differs '+e.book);
   const items=[...n.querySelectorAll('tei-list > tei-item')],labels=[...n.querySelectorAll('tei-list > tei-label')];
   const projection=x=>{x=x.cloneNode(true);x.querySelectorAll('tei-note').forEach(n=>n.remove());return x.textContent;};
   if(JSON.stringify(items.map(projection))!==JSON.stringify(e.headings)||JSON.stringify(labels.map(x=>x.textContent))!==JSON.stringify(e.labels))throw Error('Exact heading/number mismatch '+e.book);
   if(items.length!==e.entries||items[0].textContent.indexOf(e.first)!==0||items.at(-1).textContent.indexOf(e.last)!==0)throw Error('Count/endpoints');
   if(!n.textContent.includes('Whiston’s chapter headings (compiled index)')||!n.querySelector('.source-contents-note').textContent.includes('Alden & Beardsley, 1856')||!n.textContent.includes('arrangement as an index is editorial'))throw Error('Truthful designation missing');
   if(n.textContent.includes('awaits editorial approval')||n.textContent.includes('1737'))throw Error('Obsolete/misleading public note');if(n.querySelector('a'))throw Error('Speculative link');
   const ids=[...document.querySelectorAll('[id]')].map(x=>x.id);if(ids.length!==new Set(ids).size)throw Error('Duplicate DOM IDs');
   const st=x=>({fontFamily:getComputedStyle(x).fontFamily,fontSize:getComputedStyle(x).fontSize,color:getComputedStyle(x).color});const styles={heading:st(n.querySelector('tei-head')),entry:st(items[0]),numeral:st(labels[0]),provenance:st(n.querySelector('.source-contents-note'))};
   if(!Object.values(styles).every(x=>x.fontFamily.includes('LJ Coelacanth'))||!document.fonts.check('18px "LJ Coelacanth"'))throw Error('Coelacanth unavailable');
   if(n.scrollWidth>n.clientWidth+1||document.documentElement.scrollWidth>innerWidth+1)throw Error('Overflow');let surface=n;while(surface.parentElement&&getComputedStyle(surface).backgroundColor==='rgba(0, 0, 0, 0)')surface=surface.parentElement;
   const greek=document.querySelector('#greek .source-contents');if(![...greek.children].some(x=>x.localName.startsWith('tei-')))throw Error('Greek lost');const latin=document.querySelector('#latin .source-contents');
   return {book:e.book,entries:items.length,first:projection(items[0]),last:projection(items.at(-1)),styles,background:getComputedStyle(surface).backgroundColor,greek:'own contents',latin:latin.textContent==='No source table of contents is available for this witness.'?'neutral unavailable':'own contents',overflow:false,duplicateIds:0,nonClickable:true};
  },e);
  const lum=c=>c.match(/[\d.]+/g).slice(0,3).map(Number).map(v=>{v/=255;return v<=.04045?v/12.92:((v+.055)/1.055)**2.4}).reduce((a,v,i)=>a+v*[.2126,.7152,.0722][i],0);const a=lum(data.styles.entry.color),b=lum(data.background),contrast=(Math.max(a,b)+.05)/(Math.min(a,b)+.05);if(contrast<4.5)throw Error('Contrast '+contrast);
  report.checks.push({theme,...data,contrast:+contrast.toFixed(2),result:'PASS'});console.log('Whiston index',e.book,theme,data.entries);save();
  if([3,5,14,20].includes(e.book)){await snap(`AFTER_Whiston-${e.book}_${theme}.png`);await page.locator('#english tei-item').last().scrollIntoViewIfNeeded();await page.screenshot({path:path.join(__dirname,`AFTER_Whiston-${e.book}_${theme}_last.png`)});report.screenshots.push(`AFTER_Whiston-${e.book}_${theme}_last.png`);}
  if(e.book===3){await page.locator('#english tei-item[n="8"]').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(__dirname,`III8_${theme}.png`)});report.screenshots.push(`III8_${theme}.png`);}
  if(theme==='light'){
   const copied=page.url(),contents=await page.locator('#english .source-contents').textContent();await page.reload();await page.waitForFunction(()=>window.__tocReady);if(page.url()!==copied||await page.locator('#english .source-contents').textContent()!==contents)throw Error('Reload');
   await page.evaluate(()=>document.querySelector('#collapse-settings').classList.add('show'));for(const p of ['english','greek']){await page.uncheck(`#${p}-pane-select`,{force:true});await page.check(`#${p}-pane-select`,{force:true});if(page.url()!==copied)throw Error('Pane state');}
   await page.selectOption('#chapter-selector','1');await settle();if(new URL(page.url()).searchParams.has('view'))throw Error('Contents to Chapter');await page.selectOption('#chapter-selector','contents');await settle();if(new URL(page.url()).searchParams.get('view')!=='contents')throw Error('Chapter to contents');
   await page.goBack();await page.waitForFunction(()=>window.__toc.state().viewingLevel==='chapter-level');await page.goForward();await page.waitForFunction(()=>window.__toc.state().viewingLevel==='contents-level');
   const u=new URL(page.url());if(['chapter','subchapter','bamberg','niese','unit'].some(k=>u.searchParams.has(k))||u.searchParams.get('extra')!=='keep'||u.hash!=='#retained')throw Error('URL state');
   report.interactions.push({book:e.book,copyReload:'PASS',panes:'PASS',contentsChapter:'PASS',history:'PASS',unrelatedPreferences:'PASS'});
  }
 }
 for(const e of existing){const work=e.work==='bellum'?'bellum-judaicum':e.work;await open(`/${work}/?book=${e.book}&view=contents&${e.language.toLowerCase()}=${e.witness}`);const actual=await page.locator(`#${e.language.toLowerCase()} .source-contents`).evaluate(n=>({texts:[...n.children].filter(x=>x.localName.startsWith('tei-')).map(x=>x.textContent),supplements:[...n.querySelectorAll('tei-supplied')].map(x=>x.textContent)}));if(JSON.stringify(actual.texts)!==JSON.stringify(e.texts)||JSON.stringify(actual.supplements)!==JSON.stringify(e.supplements))throw Error('Existing TOC changed '+e.id);report.existing.push({id:e.id,result:'PASS'});console.log('existing',e.id);save();}
 await open('/antiquities/?book=1&view=contents');await page.evaluate(()=>document.querySelector('#collapse-settings').classList.add('show'));for(let b=2;b<=20;b++){await page.selectOption('#book-selector',String(b).padStart(2,'0'));await settle();if(new URL(page.url()).searchParams.get('view')!=='contents'||await page.locator('#english tei-item').count()!==expected[b-1].entries)throw Error('Book switching '+b);}report.bookSwitches=19;
 await open('/antiquities/?book=3&chapter=1');await page.evaluate(()=>document.querySelector('#collapse-settings').classList.add('show'));report.narrativeEnglishFont=await page.locator('#english tei-p').first().evaluate(x=>getComputedStyle(x).fontFamily);if(report.narrativeEnglishFont!==report.checks[0].styles.entry.fontFamily)throw Error('Narrative/TOC font mismatch');await page.locator('#chapter-selector').focus();await page.keyboard.press('Home');await page.keyboard.press('Enter');await settle();if(new URL(page.url()).searchParams.get('view')!=='contents')throw Error('Keyboard');report.keyboard='PASS';
 for(const b of [8,9,10]){await open(`/antiquities/?book=${b}&view=contents`);if(!await page.locator('#niese-level').isDisabled())throw Error('Citation expansion '+b);}report.nieseVIII_XStillDisabled=true;
 if(report.pageErrors.length||report.failedRequests.length)throw Error(JSON.stringify({errors:report.pageErrors,requests:report.failedRequests}));report.result='PASS';report.books=20;report.headings=256;report.themeDisplays=40;save();await browser.close();server.close();console.log('WHISTON_BUILT_SITE_PASS');
})().catch(e=>{report.result='FAIL';report.failure=String(e);save();console.error(e);server.close();process.exit(1)});
