const fs=require('fs'),path=require('path'),http=require('http'),crypto=require('crypto');
const {chromium}=require('C:/Program Files/WindowsApps/OpenAI.CodexPrimaryRuntime.v26-1007-641-0_26.1007.641.0_x64__3k8sg7r9htsxt/dependencies/node/node_modules/playwright');
const P=__dirname,root=path.resolve(P,'../..'),runtime='C:/workspace/Antiquities-Niese-20-integration-runtime-20261010';
const mode=process.argv[2]||'final',site=path.join(runtime,mode==='baseline'?'baseline-site':'final-site');
const norm=s=>s.replace(/\s+/g,' ').trim(),sha=x=>crypto.createHash('sha256').update(x).digest('hex');
function narrative(node){const c=node.cloneNode(true);c.querySelectorAll('tei-num,tei-milestone,tei-note,tei-app,tei-rdg,.niese-context-note,.niese-correspondence-note,.structural-unavailable').forEach(n=>n.remove());return [...(c.matches?.('tei-p')?[c]:[]),...c.querySelectorAll('tei-p')].filter(p=>!p.closest('tei-div2[n="0"]')).map(p=>p.textContent).join('');}
function instrument(s){s=s.replace('  bookTitle.innerText = activeWork.title;',`  window.__qa={getState:()=>({...state}),getData:()=>fullData,view:()=>viewData,antiquitiesNieseStartEntries,traditionalRows,bambergRows,traditionalRangeView,traditionalPoint,milestoneChapterNumbers,milestoneChapterView};\n  bookTitle.innerText = activeWork.title;`);s=s.replace('    syncNavigationControls();','    syncNavigationControls(); window.__qaRenderedState={...state};');return s.replace('  reload().then(() => {','  reload().then(() => { window.__qaReady=true; document.querySelector("#collapse-settings")?.classList.add("show");');}
function serve(site){return http.createServer((req,res)=>{let f=path.resolve(site,'.'+decodeURIComponent(new URL(req.url,'http://localhost').pathname));if(!f.startsWith(path.resolve(site)+path.sep)){res.statusCode=403;return res.end();}if(fs.existsSync(f)&&fs.statSync(f).isDirectory())f=path.join(f,'index.html');if(!fs.existsSync(f)){res.statusCode=404;return res.end();}let raw=fs.readFileSync(f);if(f.endsWith('renderTei.js'))raw=Buffer.from(instrument(raw.toString()));res.setHeader('Content-Type',f.endsWith('.xml')?'application/xml':f.endsWith('.json')?'application/json':f.endsWith('.js')?'text/javascript':f.endsWith('.html')?'text/html':f.endsWith('.css')?'text/css':f.endsWith('.svg')?'image/svg+xml':f.endsWith('.png')?'image/png':f.endsWith('.jpg')?'image/jpeg':'application/octet-stream');res.end(raw);});}
async function main(){
 const result={scope:mode==='baseline'?'IMMUTABLE_BASELINE_CONTAINING_VIEWS':'ACTUAL_FINAL_PRODUCTION_FULL_BOOK_CERTIFICATION',status:'RUNNING',site,started:new Date().toISOString(),books:{},errors:[],views:[],selections:[],interactions:[]};
 const port=mode==='baseline'?8939:8938,server=serve(site);await new Promise((r,j)=>{server.once('error',j);server.listen(port,'127.0.0.1',r);});
 const context=await chromium.launchPersistentContext(path.join(runtime,'browser-'+mode+'-complete'),{headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'}),page=await context.newPage();
 const origin='http://127.0.0.1:'+port;page.on('pageerror',e=>result.errors.push(String(e)));page.on('console',m=>{if(m.type()==='error')result.errors.push(m.text());});page.on('requestfailed',r=>result.errors.push(r.url()+': '+r.failure()?.errorText));
 async function open(query){await page.goto(origin+'/antiquities/?'+query,{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>window.__qaReady,{},{timeout:60000});}
 async function snapshot(){return page.evaluate(code=>{const text=eval('('+code+')'),ids=[...document.querySelectorAll('[id]')].map(n=>n.id);return {languages:Object.fromEntries(['Latin','Greek','English'].map(l=>[l,text(document.querySelector('#'+l.toLowerCase()))])),duplicates:ids.filter((id,i)=>ids.indexOf(id)!==i),note:document.querySelector('#latin .niese-correspondence-note')?.textContent||null,EnglishContext:!!document.querySelector('#english .niese-context-note'),state:window.__qa.getState()};},narrative.toString());}
 try{
  const structural=JSON.parse(fs.readFileSync(path.join(P,'EXPECTED_STRUCTURAL_RANGES.json'))),baseline=mode==='baseline'?null:JSON.parse(fs.readFileSync(path.join(P,'BASELINE_CONTAINING_BROWSER.json')));
  for(const b of [18,19]){
   const roman=b===18?'XVIII':'XIX',d=path.join(root,`review/Antiquities_Niese_Book${roman}_2026-10-09`),expected=JSON.parse(fs.readFileSync(path.join(d,'FINAL_EXPECTED_INTERVALS.json')));
   await open('book='+b);for(const l of ['greek','english'])await page.check('#'+l+'-pane-select');
   result.books[b]=await page.evaluate(()=>({alignment:[...document.querySelector('#section-selector').options].filter(o=>o.value).map(o=>o.value),legacy:window.__qa.milestoneChapterNumbers().filter(n=>Number(n)>0),traditional:window.__qa.traditionalRows('chapter').length,subchapters:window.__qa.traditionalRows('subchapter').length,bamberg:window.__qa.bambergRows().length}));
   const legacy=await page.evaluate(code=>{const q=window.__qa,text=eval('('+code+')'),d=q.getData();return q.milestoneChapterNumbers().filter(n=>Number(n)>0).map(n=>({number:n,languages:Object.fromEntries(['Latin','Greek','English'].map(l=>[l,text(q.milestoneChapterView(l,d[l],n,true))]))}));},narrative.toString());
   result.books[b].legacyRanges=legacy.map(r=>({number:r.number,languages:Object.fromEntries(Object.entries(r.languages).map(([l,t])=>[l,sha(norm(t))]))}));
   if(baseline&&JSON.stringify(result.books[b].legacyRanges)!==JSON.stringify(baseline.books[b].legacyRanges))throw Error('Legacy full endpoints changed '+b);
   const views=[{id:'book-'+b,query:'book='+b},...result.books[b].alignment.map(id=>({id:'alignment-'+b+'-'+id,query:`book=${b}&unit=${id}`})),{id:'contents-'+b,query:`book=${b}&view=contents`},...structural.filter(r=>r.book===b).map(r=>({id:r.id,row:r,query:`book=${b}&`+(r.scheme==='bamberg'?`bamberg=${Number(r.id.split('-row')[1])}`:`chapter=${r.chapter}`+(r.scheme==='subchapter'?`&subchapter=${r.subchapter}`:''))}))];
   for(const v of views){await open(v.query);const actual=await snapshot();if(baseline&&JSON.stringify(actual.duplicates)!==JSON.stringify(baseline.views.find(x=>x.id===v.id).existingDuplicateIDs))throw Error('New duplicate DOM IDs '+v.id);const hashes=Object.fromEntries(Object.entries(actual.languages).map(([l,t])=>[l,sha(norm(t))]));if(v.row)for(const l of ['Latin','Greek','English'])if(norm(actual.languages[l])!==norm(v.row.languages[l].text))throw Error('Independent full structural interval '+v.id+' '+l);if(baseline&&JSON.stringify(hashes)!==JSON.stringify(baseline.views.find(x=>x.id===v.id).hashes))throw Error('Containing view changed '+v.id);result.views.push({id:v.id,book:b,query:v.query,hashes,existingDuplicateIDs:actual.duplicates,status:'PASS'});}
   if(mode==='baseline')continue;
   await open(`book=${b}&niese=1`);
   const census=await page.evaluate(()=>{const q=window.__qa,d=q.getData();return {menu:[...document.querySelector('#niese-selector').options].filter(o=>o.value).map(o=>Number(o.value)),Greek:q.antiquitiesNieseStartEntries('Greek',d.Greek).map(e=>e.number),Latin:q.antiquitiesNieseStartEntries('Latin',d.Latin).map(e=>e.number)};});
   if(JSON.stringify(census.menu)!==JSON.stringify(expected.map(e=>e.number))||JSON.stringify(census.Greek)!==JSON.stringify(census.menu))throw Error('Full Greek/menu review census '+b);result.books[b].reviewCensus=census;
   for(const e of expected){await page.evaluate(async n=>{const menu=document.querySelector('#niese-selector');menu.value=String(n);menu.dispatchEvent(new Event('change',{bubbles:true}));const start=Date.now();await new Promise((resolve,reject)=>{const check=()=>{if(window.__qaRenderedState?.nieseNum===String(n)&&['latin','greek','english'].every(l=>document.querySelector(`#${l} [n="${n}"][type^="niese-"]`)))return resolve();if(Date.now()-start>30000)return reject(Error('All panes did not finish rendering '+n));setTimeout(check,5);};check();});},e.number);const a=await snapshot();if(norm(a.languages.Greek)!==norm(e.Greek)||norm(a.languages.English)!==norm(e.English)||!a.EnglishContext||a.duplicates.length){fs.writeFileSync(path.join(P,'FINAL_DIFFERENCE.json'),JSON.stringify({b,expected:e,actual:a},null,2));throw Error('Greek/English review selection '+b+'.'+e.number);}if(e.safe_Latin_interval&&(norm(a.languages.Latin)!==norm(e.Latin)||a.note!==e.qualification)){fs.writeFileSync(path.join(P,'FINAL_DIFFERENCE.json'),JSON.stringify({b,expected:e,actual:a},null,2));throw Error('Secure Latin interval '+b+'.'+e.number);}if(e.unavailable){const u=await page.locator('#latin .structural-unavailable').textContent();if(norm(a.languages.Latin)!==''||!u.includes(e.qualification)||!u.includes('No nearby text has been substituted.'))throw Error('Specific approved unavailable notice '+b+'.'+e.number);}else if(e.qualification&&await page.locator('#latin .niese-correspondence-note').getAttribute('role')!=='note')throw Error('Qualification accessibility '+b+'.'+e.number);result.selections.push({book:b,number:e.number,Greek:'EXACT_PASS',English:'PRESERVED_CONTEXT_PASS',Latin:e.safe_Latin_interval?'EXACT_INTERVAL_PASS':'APPROVED_UNAVAILABLE_PASS',pending:e.pending,duplicateIDs:0});if(e.number%75===0)console.log('Review',b,e.number);}
   const cases=b===18?[1,6,7,8,63,64,93,94,95,116,117,118,119,215,216,217,218,256,257,258,378,379]:[1,187,188,189,291,292,293,...Array.from({length:14},(_,i)=>353+i)];
   for(const n of cases){await open(`book=${b}&niese=${n}`);await page.reload();await page.waitForFunction(()=>window.__qaReady);if(n<expected.length){await page.click('#niese-next');await page.waitForFunction(n=>window.__qaRenderedState?.nieseNum===String(n),n+1);await page.click('#niese-previous');await page.waitForFunction(n=>window.__qaRenderedState?.nieseNum===String(n),n);await page.goBack();await page.waitForFunction(n=>window.__qaRenderedState?.nieseNum===String(n),n+1);await page.goForward();await page.waitForFunction(n=>window.__qaRenderedState?.nieseNum===String(n),n);}else if(!await page.locator('#niese-next').isDisabled())throw Error('Book terminal next');if(n===1&&!await page.locator('#niese-previous').isDisabled())throw Error('Opening previous');result.interactions.push({book:b,number:n,reloadPreviousNextHistory:'PASS'});}
   await open(`book=${b}&niese=${b===18?118:365}`);for(const l of ['greek','english']){await page.uncheck('#'+l+'-pane-select');if(await page.locator('#'+l).isVisible())throw Error('Hide pane '+l);await page.check('#'+l+'-pane-select');if(!await page.locator('#'+l).isVisible())throw Error('Show pane '+l);}
   for(const theme of ['light','dark']){await page.evaluate(t=>setTheme(t),theme);await page.waitForTimeout(800);await page.screenshot({path:path.join(P,'evidence',b+'-reader-'+theme+'.png'),fullPage:true});}
  }
  if(result.errors.length)throw Error('Browser errors '+JSON.stringify(result.errors));result.status='PASS';
 }catch(e){result.status='FAIL';result.failure=String(e);throw e;}finally{result.finished=new Date().toISOString();fs.writeFileSync(path.join(P,mode==='baseline'?'BASELINE_CONTAINING_BROWSER.json':'FINAL_BROWSER.json'),JSON.stringify(result,null,2)+'\n');await context.close();await new Promise(r=>server.close(r));}
 console.log(JSON.stringify({status:result.status,mode,views:result.views.length,selections:result.selections.length,secureLatin:result.selections.filter(r=>r.Latin==='EXACT_INTERVAL_PASS').length,interactionCases:result.interactions.length}));
}
module.exports={serve,instrument,narrative};if(require.main===module)main().catch(e=>{console.error(e);process.exitCode=1;});
