const {fs,path,P,norm,sha,session}=require('./browser_common.cjs');
async function main(){const mode=process.argv[2]||'baseline',s=await session(mode),r={scope:'OTHER_WORKS_SOURCE_CONTROLS_LEGACY_URLS_CONTENTS_AND_PRECISE_BASELINE_EXCEPTIONS',mode,status:'RUNNING',started:new Date().toISOString(),routes:[],knownExceptions:[],errors:s.errors},base=mode==='baseline'?null:JSON.parse(fs.readFileSync(path.join(P,'BASELINE_OTHER_CONTROLS.json')));
r.sourceBuild=mode==='baseline'?'003ac796021890dde4b3d8ff152100f386280b3c':JSON.parse(fs.readFileSync(path.join(P,'CANDIDATE_BUILD.json'))).source_commit;
try{
 await s.open('book=15');const lastBamberg=await s.page.evaluate(()=>window.__qa.bambergRows().at(-1).id);
 const routes=[...Array.from({length:20},(_,i)=>({work:'antiquities',query:'book=20&chapter='+(i+1)})),{work:'antiquities',query:'book=15&chapter=7'},{work:'antiquities',query:'book=15&bamberg='+lastBamberg},{work:'antiquities',query:'book=15&view=contents'},...Array.from({length:5},(_,i)=>({work:'antiquities',query:'book='+(16+i)})),{work:'antiquities',query:'book=20&view=contents'},{work:'bellum-judaicum',query:'book=1&niese=1&latin=cardwell'},{work:'bellum-judaicum',query:'book=1&niese=1&english=whiston'},{work:'bellum-judaicum',query:'book=1&niese=1&english=lodge1602'},{work:'bellum-judaicum',query:'book=4&chapter=1'},{work:'deh',query:'book=1&chapter=1&unit=1'},{work:'contra-apionem',query:'book=2&unit=1'}];
 for(const v of routes){await s.open(v.query,v.work);const a=await s.snapshot();const visible=await s.page.evaluate(()=>({headings:[...document.querySelectorAll('#english tei-head,#english tei-note[subtype="provenance"]')].map(n=>[n.textContent,getComputedStyle(n).fontStyle]),sourceContents:[...document.querySelectorAll('#latin a[href],#greek a[href],#english a[href]')].map(n=>[n.textContent,n.getAttribute('href')])}));const row={...v,languages:Object.fromEntries(Object.entries(a.languages).map(([l,t])=>[l,sha(norm(t))])),sourceIDs:a.sourceIDs,state:a.state,duplicates:a.duplicates,visible};const p=new URLSearchParams(v.query);for(const l of ['Latin','Greek','English'])if(p.has(l.toLowerCase())&&a.state.sources[l]!==p.get(l.toLowerCase()))throw Error('Requested source not active '+v.query);if(base&&JSON.stringify(row)!==JSON.stringify(base.routes.find(x=>x.work===v.work&&x.query===v.query)))throw Error('Protected control changed '+v.work+'?'+v.query);r.routes.push(row);}
 await s.open('book=1&bamberg=B78-table1-row005');const links=await s.page.evaluate(()=>[...document.querySelectorAll('#latin a[href],#greek a[href],#english a[href]')].map(a=>a.getAttribute('href')).filter(h=>h.startsWith('undefinednote_')));if(links.length!==3)throw Error('Known apparatus link signature');const targets=[];for(const href of new Set(links)){const response=await s.page.request.get(new URL(href,s.page.url()).href);if(response.status()!==404)throw Error('Known apparatus link status');targets.push({href,status:404});}r.knownExceptions.push({case:'Inherited Book-I apparatus links',links,targets,excludedFromNewErrors:true});
 if(r.errors.length)throw Error('Unexpected errors before unsupportedI.1 '+JSON.stringify(r.errors));
 const errorPromise=s.page.waitForEvent('pageerror',{timeout:30000});await s.page.goto('http://127.0.0.1:8921/antiquities/?book=1&niese=1',{waitUntil:'domcontentloaded'});const error=String(await errorPromise),inventory=await s.page.evaluate(()=>({selected:document.querySelector('#niese-selector').value,firstSupported:[...document.querySelector('#niese-selector').options].find(o=>o.value)?.value}));if(error!=="TypeError: Cannot read properties of null (reading 'querySelector')"||inventory.firstSupported!=='27')throw Error('UnsupportedI.1 signature changed');r.knownExceptions.push({case:'UnsupportedI.1',error,inventory,excludedFromSelectableCount:true});if(base&&JSON.stringify(r.knownExceptions)!==JSON.stringify(base.knownExceptions))throw Error('Known exception difference');if(r.errors.length!==1||r.errors[0].message!==error)throw Error('Additional errors');r.expectedUnsupportedErrors=r.errors.splice(0);r.status='PASS';
}catch(e){r.status='FAIL';r.failure=String(e);throw e;}finally{r.finished=new Date().toISOString();fs.writeFileSync(path.join(P,mode==='baseline'?'BASELINE_OTHER_CONTROLS.json':'FINAL_OTHER_CONTROLS.json'),JSON.stringify(r,null,2)+'\n');await s.close();}console.log(JSON.stringify({status:r.status,routes:r.routes.length,knownExceptions:r.knownExceptions.length}));}
main().catch(e=>{console.error(e);process.exitCode=1;});
