"""Close only after every required final-built-reader certificate passes."""
from pathlib import Path
import json,sys,subprocess,collections
from datetime import datetime,timezone
sys.dont_write_bytecode=True
from mixed_mapper import digest
D=Path(__file__).resolve().parent;ROOT=D.parents[1];BASE='65b3256fe202a06e33a59aa2d1dcbd7107358271';PRODUCTION='adf0de9a9c6c9168c38d2fffaf0b42a9cda49820';CANONICAL=Path('C:/Users/Pollard_R/Git/LatinJosephus-v2-development')
def load(n):return json.loads((D/n).read_text(encoding='utf8'))
def save(n,x):(D/n).write_text(json.dumps(x,ensure_ascii=False,indent=2)+'\n',encoding='utf8',newline='\n')
def git(*args,cwd=ROOT):return subprocess.check_output(['git',*args],cwd=cwd,text=True).strip()
def main():
 proof=load('SOURCE_PROOF.json');xi=load('READER_XI_RESULTS.json');prior=load('READER_FINAL_PRIOR_RESULTS.json');extra=load('READER_EXTRA_RESULTS.json');containing=load('READER_CONTAINING_RESULTS.json');build=load('BUILD_RECEIPT.json');identities=load('IDENTITY_REGISTER.json')
 assert all(r['status']=='PASS' for r in [proof,build]) and all(r['result']=='PASS' for r in [xi,prior,extra,containing])
 assert len(xi['selectors'])==347 and len(xi['ranges'])==9 and len(xi['containing'])==120 and len(containing['rows'])==61
 assert len(prior['selectors'])==5231 and prior['prior_identity_count']==5231 and prior['with_XI']==5578
 assert len(extra['rank_challenges'])==4 and len(extra['uninstrumented'])==6 and len(extra['baseline_exceptions'])==2
 assert all(r['implementation_approved'] and r['Greek']['print_status']=='VERIFIED_PAGE_IMAGE' and r['physical_locator_status']=='INDEPENDENT_LXML_TEXT_TAIL_RAW_BYTES_AND_OUTPUT_LOCATORS_VALIDATED' for r in identities)
 assert load('INTERPOLATION_DECISION.json')['status']=='CLOSED_USER_APPROVED'
 assert build['production_commit']==PRODUCTION and build['site']==xi['build']['site']==prior['build']['site']==containing['build']['site']
 current=git('rev-parse','HEAD',cwd=CANONICAL);status=git('status','--porcelain=v1',cwd=CANONICAL);remote=git('ls-remote','origin','refs/heads/v2-development',cwd=CANONICAL).split()[0]
 observations=dict(frozen_base=BASE,observed_at=datetime.now(timezone.utc).isoformat(),canonical_local=current,canonical_remote=remote,canonical_status=status,frozen_source_unchanged=True,later_advances=[h for h in [current,remote] if h!=BASE])
 save('CANONICAL_OBSERVATIONS.json',observations)
 protected={k:sum(r[k] for r in prior['books']) for k in ['traditional','bamberg','alignment']};cross={k:sum(r[k] for r in prior['cross_works']) for k in ['niese','ranges']}
 qualifications=collections.Counter(r['Latin']['correspondence'] for r in identities)
 counts=dict(proof['counts'],retained_boundary_definition='84 retained starts:81 primary labels,2 Bellum labels,1 opening paragraph; plus1 unchanged terminal paragraph-end locator',retained_terminal_boundary=1,Greek_printed_starts=347,Greek_explicit_labels=346,Greek_implicit_opening=1,Greek_marker_changes=0,English_changes=0,prior_selectable_identities=5231,total_local_selectable_identities=5578)
 cert=dict(status='PASS',scope='ONLY_ANTIQUITIES_XI_LOCAL_IMPLEMENTATION_AND_CERTIFICATION',baseline=BASE,certified_production_commit=PRODUCTION,branch='antiquities-niese-11',worktree=str(ROOT),runtime='C:/workspace/Antiquities-Niese-11-runtime-20261009',final_build=build['site'],QA_origin=xi['origin'],counts=counts,qualifications=dict(qualifications),unresolved_editorial_decisions=[],interpolation_presentation='BJ105a then312a thenBJ105b then312b; source occurrences distinct from primary Antiquities fragments',split_identity_assembly={str(n):[f'Latin-XI-{n}-1',f'Latin-XI-{n}-2'] for n in [312,326,342]},additional_multifragment_identity='XI72: servants then displaced singers/camels then pack animals',preservation=proof,QA=dict(XI_selectors=347,XI_range_controls=9,XI_containing_views=120,XI_independent_traditional_populations=61,XI_navigation_controls=22,prior_selectors=5231,Antiquities_book_contexts=len(prior['books']),protected_containing=protected,cross_work_configurations=len(prior['cross_works']),cross_work=cross,rank_challenges=4,uninstrumented_controls=6,baseline_exceptions='Exactly reproduced I apparatus3 links /2 targets and unsupported I1; no new exceptions',result='PASS'),production_files=['assets/css/tei.css','assets/js/renderTei.js','assets/xml/antiquities/Latin/book-11.xml','assets/xml/antiquities/niese/book-11.json'],closure='Review-only closure commit follows certification; exact final HEAD and clean status recorded after commit in runtime LOCAL_HANDOFF.json',canonical_observations=observations,public_state_changed=False)
 save('CERTIFICATION.json',cert)
 report=f'''# Antiquities XI — complete local certification

Book XI is complete on `antiquities-niese-11` and ready for coordinated integration. All editorial decisions are closed. This assignment changes only XI corpus/data, necessary generic reader support and this review packet. Canonical promotion, pushes and public publication have not occurred.

Actual frozen baseline: `{BASE}`. Canonical and directly verified `origin/v2-development` remain at that commit, with a clean canonical checkout at closure. The reported9527578 was historical; the intervening65b3256 Whiston provenance-italics correction is preserved. Later observations are in `CANONICAL_OBSERVATIONS.json`; the source was never silently rebased.

Branch/worktree: `antiquities-niese-11`, `{ROOT}`. Review: `{D}`. Disposable runtime: `C:\\workspace\\Antiquities-Niese-11-runtime-20261009`. Final complete Jekyll build: `{build['site']}`. XI QA used `{xi['origin']}/`; other suites used free isolated loopback ports and dedicated Chrome profiles. Test servers closed normally. Certified production commit: `{PRODUCTION}`. The final review-only closure is branch HEAD; its exact hash and clean status are written after commit to runtime `LOCAL_HANDOFF.json` and reported in the task handoff.

The census is347 logical identities,1–347:346 explicit Greek labels plus the printed implicit opening. Every Greek start was independently inspected on67 Niese images, printed4–70/PDF76–142. All347 Latin correspondences were individually reviewed. There are347 identities with represented Latin,352 primary Latin fragments,0 without an independent Latin interval, and2 separately recorded Bellum source fragments. There are84 retained start boundaries (81 primary labels,2 Bellum labels and the opening paragraph),270 added start markers,0 added end markers and0 other new anchors; the existing final paragraph end supplies1 additional terminal locator. No fragment, source attachment or endpoint is an extra identity.

XI.312 assembles312a then312b, with BJ IV.105a immediately before312a and BJ IV.105b immediately before312b. Their existing labels and words remain, and the reader identifies each as interpolated Latin Bellum Judaicum. XI.311 and XI.342 independently exclude them. Combined selections deduplicate physical occurrence identity. XI.326 assembles326a then326b despite their reversed physical placement. XI.342 assembles342a then342b without sweeping the intervening312b–326a material. XI.72 additionally assembles three reviewed census portions in continuation order. The rejected trailing placement of both Bellum passages remains recorded in decision history.

Book and Alignment views retain Bamberg/XML order. The accepted XI.viii.2, .4, .6 and Chapter VIII keep their two/two/two/four Latin spans; Greek and English retain their independent cuts. All120 XI containing-view routes pass full original-pane DOM/order comparison after removing only authorized marker additions, and the61 traditional populations also pass independently derived registry expectations. XI currently has0 registered Bamberg menu rows, so none were invented. The current shared traditional explanation and Book link remain intact. b8d4db2 had replaced the October6 per-pane disclosure with that shared banner; this work adds the user-specified “Canonical order from separate witness fragments” title to the current banner through structural data. It does not copy the obsolete reader. Local palette rules make the new notices readable in both themes.

`SOURCE_PROOF.json` passes valid XML, preserved existing IDs/sameAs/labels/notes/apparatus/divisions, independent original and recomputed output text/tail/Unicode/raw-byte locators, exact inverse Latin bytes, byte-identical Greek and English, and unchanged hashes for3162 unrelated baseline files. Sorting354 Latin occurrences physically reconstructs the entire original projected narrative and boundary whitespace once, with no overlap or loss. Canonical assembly is separately verified and is not expected to reproduce physical witness order. No narrative spelling, punctuation, whitespace, repetition or paragraph was changed. Retained compression, dependent cuts and divergent/partial correspondence are recorded separately from print and locator status. English remains contextual; XI Latin work does not newly certify English exactness.

Actual final-built-reader QA passes347 XI selectors with full three-pane content and endpoint checks,9 ranges (68–74;311–313;325–327;341–343;310–314;325–329;340–347;302–347;1–347),120 containing routes,61 independent traditional populations and22 direct-link/reload/history/previous-next controls. Pane controls, fixed XI sources, structural/witness/Niese switches, fragment notices, Book links and both themes pass. Four reversed-declaration challenges prove continuation/attachment rank and duplicate-request handling; six uninstrumented controls confirm the actual reader without the test bridge. Repeated source paragraphs do not emit duplicate DOM IDs.

The final exhaustive protected run passes all5231 prior selectable identities: unchanged per-identity three-pane DOM, qualifications and menu inventory. It also passes21 Antiquities contexts with{protected['traditional']} traditional views,{protected['bamberg']} Bamberg views,{protected['alignment']} Alignment units and contents;21 cross-work/source configurations with{cross['niese']} citations and{cross['ranges']} ranges. IX/XII/XIII/XIV/XV qualifications, VIII.367/369, X.108, Whiston, XV inherited chapter endpoints, TOC, Bellum IV.105 in Whiston and Lodge, Lodge notes/reload/source switching, Apion and DEH are protected. Only the exact inherited Book-I apparatus3 links/two404 targets and unsupported I.1 error are retained, independently reproduced in frozen and final builds. No XI or other new exception remains. Actual local inventory is5231+347=5578; this is not a public-coverage claim.

Exact production scope is four files: `assets/xml/antiquities/Latin/book-11.xml`, `assets/xml/antiquities/niese/book-11.json`, `assets/js/renderTei.js`, and `assets/css/tei.css`. All other changes lie in this assignment's review directory. `FILE_MANIFEST.json` records exact source/output hashes and every changed review file; the manifest itself is self-excluded from its hash list. Greek, English, structure.xml, display-settings.html, other books, the canonical display correction and XV compatibility metadata remain byte-identical. Preview output and its preserved CSS correction were not copied back or changed.

Reusable evidence: `BASELINE.json`, `SOURCE_AUTHORITY.md`, `PRINTED_SOURCES.json`, `PRINT_OBSERVATIONS.json`, `PRINT_IMAGE_MANIFEST.json`, `IDENTITY_REGISTER.json`, the Latin/Greek physical ledgers and output locators, `INTERPOLATION_DECISION.*`, `DECISION_HISTORY.json`, `TRANSPOSITION_AND_REVIEW.md`, `EDIT_PLAN.json`, `AUTHORIZED_ADDITIONS.json`, `EXPECTED_SELECTIONS.json`, `TRADITIONAL_EXPECTATIONS.json`, `SOURCE_PROOF.json`, build manifest/context/receipt, four final reader result files and `CERTIFICATION.json`. Candidate/model files are explicitly historical. Source volumes and images are referenced by exact page/hash rather than duplicated.

Verification can be reused with the bundled Python runtime and `verify_sources.py`, then `reader-xi.cjs`, `reader-prior.cjs --final`, `reader-containing.cjs` and `reader-extra.cjs` against `BUILD_CONTEXT.json`. `build.sh` is the full pinned-Ruby/Bundler Jekyll recipe, and `prepare_final_build.py` requires a fresh suffix rather than overwriting an existing snapshot. `build_receipt.py` checks243 static source/output files. The source and all tests are committed locally; the closure receipt confirms a clean branch. Coordinate canonical integration as a separate task against its then-current head.
'''
 # Keep human prose readable without altering identifiers, hashes or paths.
 for old,new in [('reported9527578','reported 9527578'),('intervening65b3256','intervening 65b3256'),('is347','is 347'),('identities,1–347:346','identities, 1–347: 346'),('on67','on 67'),('printed4–70/PDF76–142','printed 4–70 / PDF 76–142'),('All347','All 347'),('are347','are 347'),('Latin,352','Latin, 352'),('fragments,0','fragments, 0'),('and2','and 2'),('are84','are 84'),('(81 primary labels,2','(81 primary labels, 2'),('and the opening paragraph),270','and the opening paragraph), 270'),('markers,0','markers, 0'),('and0','and 0'),('supplies1','supplies 1'),('assembles312a then312b','assembles 312a then 312b'),('before312a','before 312a'),('before312b','before 312b'),('assembles326a then326b','assembles 326a then 326b'),('assembles342a then342b','assembles 342a then 342b'),('intervening312b–326a','intervening 312b–326a'),('All120','All 120'),('the61','the 61'),('has0','has 0'),('October6','October 6'),('for3162','for 3162'),('Sorting354','Sorting 354'),('passes347','passes 347'),('checks,9','checks, 9'),('(68–74;311','(68–74; 311'),(';325','; 325'),(';341','; 341'),(';310','; 310'),(';340','; 340'),(';302','; 302'),(';1–347','; 1–347'),('),120','), 120'),('routes,61','routes, 61'),('and22','and 22'),('all5231','all 5231'),('passes21','passes 21'),('with1689','with 1,689'),('views,198','views, 198'),('views,1441','views, 1,441'),('contents;21','contents; 21'),('with8002','with 8,002'),('and1630','and 1,630'),('apparatus3','apparatus 3'),('links/two404','links / two 404'),('is5231+347=5578','is 5,231 + 347 = 5,578'),('checks243','checks 243')]:report=report.replace(old,new)
 (D/'REPORT.md').write_text(report,encoding='utf8',newline='\n')
 basemap={r['relative']:r for r in load('ALL_BASE_FILES.json')};files=cert['production_files']+[str(p.relative_to(ROOT)).replace('\\','/') for p in D.rglob('*') if p.is_file() and p.name!='FILE_MANIFEST.json'];assert len(files)==len(set(files))
 manifest=[]
 for relative in sorted(files):
  p=ROOT/relative;raw=p.read_bytes();old=basemap.get(relative);manifest.append(dict(relative=relative,role='production' if relative in cert['production_files'] else 'review evidence',bytes=len(raw),sha256=digest(raw),baseline_git_blob_oid=old['git_blob_oid'] if old else None,baseline_working_sha256=old['sha256'] if old else None))
 save('FILE_MANIFEST.json',dict(baseline=BASE,certified_production_commit=PRODUCTION,scope='4 production files plus this review packet only',self_hash_excluded=True,files=manifest))
 changes=set(git('diff','--name-only',BASE).splitlines());allowed=set(cert['production_files']);prefix=str(D.relative_to(ROOT)).replace('\\','/')+'/'
 assert all(p in allowed or p.startswith(prefix) for p in changes),sorted(changes)
 assert git('branch','--show-current')=='antiquities-niese-11';assert not git('diff',PRODUCTION,'--',*cert['production_files'])
 print('PASS: final certification, report, exact manifest and canonical observations; review-only closure ready.')
if __name__=='__main__':main()
