import sys,json
sys.dont_write_bytecode=True
from review_batch import cuts,pages,save,D
cuts([
 (251,244,'Audiens autem iam','Departure to reward Mordecai.'),(252,244,'Cumque serui renuntiassent','Haman admission and inquiry.'),(253,244,'Aman uero putans','Haman supposes himself intended.'),(254,244,'et dixit so uis','Direct advice on royal horse and clothing.'),(255,244,'Igitur aman','Command to perform that honour for Mordecai.'),(256,244,'Post quam haec preater','Outside encounter.'),(257,244,'dum ille nesciens','Mordecai mistaken expectation and rebuke.'),(258,244,'et super equum','Mounting and proclamation.'),(259,244,'Cumque totam','Circuit, return and household counsel.'),
 (260,260,'dumque haec','Eunuch arrives during counsel; inherited paragraph start.'),(261,260,'sabuchadas uero','Eunuch notices gallows.'),(262,260,'Cumque rex una','Banquet and renewed inquiry.'),(263,260,'neque enim molestum','Repeated promise and expectation.'),(264,260,'Itaque interrogante','Esther petition.'),(265,260,'Tunc rex ad hoc','King asks author; Esther identifies Haman.'),(266,260,'ad quodam obstipuit','Alarm, departure and eunuch identification of gallows.'),(267,260,'Quod rex audien','King orders hanging; Latin fifty cubits retained.'),(268,260,'Unde mihi','Author moral observation.'),
 (269,269,'Itaque aman','Death, property and ring.'),(270,269,'donauit uero regina','Esther gives property and requests reversal.'),(271,269,'Cui rex','Permission and sealed letters.'),(272,269,'Scribas ergo','Scribes summoned for counterdecree.'),(273,269,'Rex magnus','Salutation and abuse of generosity.'),(274,269,'sed datam si gloriam','Attack on benefactors and ingratitude.'),(275,269,'Et in tantum uesanie','False accusations and naive royal hearing; transmitted syntax retained.'),
 (276,269,'quae res et ex','Historical examples, present experience and policy; Latin comparison differs from Greek negation.'),(277,269,'Et ut manifestius','Expanded transition introduces Haman pedigree and favours; Latin Macedonian identification retained.'),(278,269,'in tantum arrogantiae','Attempt against king, Esther and Mordecai; Macedonian transfer retained.'),(279,269,'Nos autem','Jewish innocence, divine protection and letter cancellation.'),(280,269,'pro quo scelere','Public punishment; Greek honour clause compressed.'),(281,269,'Hoc autem edictum','Publication, Jewish laws, help and appointed day.'),(282,269,'hanc enim diem','Providential reversal and remembrance.'),(283,269,'Omnis autem','Penalty for refusal and concluding decree.'),
 (284,284,'Igitur equites','Couriers and Mordecai honours.'),(285,284,'praeterea gaudium','Joy and other peoples; Latin omits Greek circumcision statement.'),(286,284,'Nam duodecimo','Date and instruction; Latin fourteenth versus Greek thirteenth retained.'),(287,284,'Tunc persides','Provincial officials honour Jews.'),(288,284,'Post quam edictum','Five hundred killed in Susa.'),(289,284,'Cumque rex peremptorum','Esther requests continuation and hanging sons.'),(290,284,'Quod quidem','Royal assent, renewed action and no plunder; Latin omits three hundred figure.'),(291,284,'interfecti sunt etiam','Provincial deaths and next-day feast; Latin seventy-six thousand versus Greek seventy-five thousand retained.'),(292,284,'Similiter autem','Susa feast and continuing custom.'),(293,284,'scripsit etiam','Mordecai directs continued observance.'),(294,284,'quod in his','Reason: salvation and retaliation.'),(295,284,'Unde praedictos','Feast name and Mordecai office.'),(296,284,'Tam iudęi','Jewish freedom and Artaxerxes conclusion.'),
 (297,297,'Defuncto autem helia','Priestly succession, temple profanation and tax; transmitted anno versus lamb wording retained.'),(298,297,'Hoc autem exhuius','Cause and promise to Jesus.'),(299,297,'Que confidentia','Temple dispute and unprecedented fratricide.'),(300,297,'Unde nec deus','Divine punishment and Bagoses rebuke.'),(301,297,'Ego peremptore','Reply, entry and punishment; prevention of entry omitted and Latin anno septimo retained.')
])
x=json.loads((D/'review_choices.json').read_text(encoding='utf8'));x['qualified'].update({'267':'transmitted-numerical-divergence','275':'transmitted-syntactic-divergence','276':'transmitted-comparative-divergence','277':'transmitted-pedigree-divergence','278':'transmitted-expansion','280':'compressed-correspondence','285':'partial-correspondence','286':'transmitted-numerical-divergence','290':'partial-correspondence','291':'transmitted-numerical-divergence','297':'transmitted-wording-divergence','301':'partial-correspondence'});save('review_choices.json',x)
pages([
 (120,list(range(228,233)),'Left main margin:228 shares preceding salvation-ending line;229 VI.8;230 previous deliverance-ending line;231 previous laws-ending line;232 previous garment-ending line.'),
 (121,list(range(233,238)),'Right main margin:233 line2 after beauty-ending clause;234 VI.9;235 approach and royal attire;236 on preceding varied-attire-ending line;237 near foot after collapse.'),
 (122,list(range(238,245)),'Left main margin:238 first line after previous fear clause;239 permission-ending line;240 reassurance-ending line;241 speech-ending line;242 half-kingdom promise line;243 inquiry-ending line;244 VI.10.')
])
