from reconnaissance import *
from mixed_mapper import Book

def main():
    d=packet(18); rows=json.loads((d/'IDENTITIES.json').read_text(encoding='utf8'))
    g=Book(raw=(d/'frozen-inputs/Greek.xml').read_bytes()); l=Book(raw=(d/'frozen-inputs/Latin.xml').read_bytes())
    r=rows[0]; initial={k:r[k] for k in ['Greek_start','Greek_text','Greek_locator']}
    at=g.stream.index('Κυρίνιος'); assert at==34
    r.update(Greek_start=at,Greek_text=g.stream[at:r['Greek_end']],Greek_locator=g.locate(at),Greek_physical_start=dict(target='trad-greek-LOEB-18-Chapter-1-0',edge='after',reason='Existing exact narrative-opening anchor after preserved duration notice; no duplicate physical ID proposed.'))
    save(d/'OPENING_AND_PARATEXT_REVIEW.json',dict(book=18,implicit_identity=1,original_machine_candidate=initial,corrected_narrative_start=r['Greek_locator'],source_notice=g.stream[:at],notice_disposition='Preserved in source and containing views; excluded from exact narrative identity1.',existing_anchor=r['Greek_physical_start'],print=dict(PDF_page=154,printed_page=140,examined=True,image='evidence/Niese-IV-PDF154.jpg'),source_TOC_print_pages=[138,139],source_TOC_PDF_pages=[152,153],TOC_visually_reviewed=True,Latin_TOC_and_argument='Current chapter0 contents, literal ordinals and two argument heads individually read and retained; not executable Niese starts.',Greek_subscription='Printed on p209; no subscription text occurs in the source XML. No subscription supplied.',Latin_terminal='Current XML closes directly after 379 narrative; no extra subscription or niese-end needed.'))
    u=next(u for u in l.units if u['id']=='latin-book18-num211'); split=u['text'].index('Et tunc quidem in his')
    neighbours=[dict(number=n,locator=rows[n-1]['candidate']['locator'],text=rows[n-1]['Greek_text']) for n in [215,218]]
    inspected_ids={r['Latin_alignment_paragraph'] for r in rows}
    unseen=[dict(id=u['id'],text=u['text']) for u in l.units if u['id'] not in inspected_ids]
    assert all(not z['text'] for z in unseen)
    search={q:[dict(id=v['id'],match=m.group(0),context=v['text'][max(0,m.start()-90):m.end()+90]) for v in l.units for m in re.finditer(q,v['text'],re.I)] for q in ['galb','astrol','genet','natiuit','augur','praesag|presag']}
    result=dict(book=18,numbers=[216,217],status='HUMAN_EDITORIAL_CHOICE_PENDING',recommendation='A',Greek=[dict(number=n,text=rows[n-1]['Greek_text'],locator=rows[n-1]['Greek_locator']) for n in range(214,220)],Latin_full_paragraph=u['text'],shared_transition_locator=l.locate(u['book_start']+split),Latin_surviving_neighbours=neighbours,full_witness_review=dict(narrative_paragraphs=57,all_aligned_narrative_paragraphs_individually_read=True,remaining_mapper_units=unseen,remaining_units_note='Chapter0 excluded from narrative mapper; original chapter0 and argument separately read.',search=search),Niese=dict(printed_page=179,PDF_page=193,image='evidence/Niese-IV-PDF193.jpg',examined=True),Loeb=dict(volume='IX',edition='1965',printed_pages=[132,133,134,135],PDF_pages=[148,149,150,151],images=[f'evidence/Loeb-IX-PDF{p:03}.jpg' for p in range(148,152)],examined=True,apparatus_observation='Printed Greek p134 apparatus explicitly reports sections216–217 omitted in Latin; this supports but does not replace review of the current transcription.'),choices=[dict(choice='A',disposition='Both 216 and217 unavailable as independent Latin intervals in this transcription. Greek and contextual English remain selectable; notes describe absence without inferring cause.'),dict(choice='B',disposition='216 unavailable; represent217 as a compressed overlapping reference in the opening of Latin218, explicitly qualified. The same physical occurrence must not be claimed as an independent exact interval.')],reason='Latin215 passes directly to the remorse account of218. No account of casting horoscopes, Galba or general reliance on divination is expressed in the full current Latin narrative. The opening of218 refers back to the immediately preceding succession omen and does not independently express217.',production_applied=False)
    for n in [216,217]:
        rows[n-1].update(print_review_status='VISUALLY_REVIEWED',print_evidence=dict(edition='Niese IV, 1890',printed_page=179,PDF_page=193,image='evidence/Niese-IV-PDF193.jpg',visible_numeral=str(n),observation='Numeral and complete adjacent Greek examined; independent Loeb comparison also examined.'),Latin_review_status='FULL_WITNESS_REVIEW_COMPLETED_HUMAN_REPRESENTATION_PENDING',candidate=dict(available=False,correspondence='UNAVAILABLE_IN_THIS_TRANSCRIPTION_PROPOSED',locator=None,approved=False,case='CASE_216_217.json',reason=result['reason'],note='No corresponding passage is expressed in this Latin transcription. The cause of this difference is not established. Greek and contextual English remain independently available.'))
    save(d/'CASE_216_217.json',result);save(d/'IDENTITIES.json',rows)
    out='# XVIII.216–217: unavailable Latin passage or overlapping reference\n\nStatus: pending focused editorial choice. Recommendation: **A**, no independent Latin interval for either identity. No production edit has been applied.\n\nNiese IV (1890), printed p179 / PDF193, and Loeb IX (1965), printed pp132–135 / PDF148–151, were visually examined. Both show216 on Tiberius\'s astrology and Galba, and217 on general trust in divination. Loeb\'s printed Greek apparatus at p134 reports216–217 absent in Latin. The current Latin witness was reviewed in full, including the source-only contents and argument. There is no Galba or corresponding general astrology account displaced elsewhere in this book.\n\n'
    for z in result['Greek']:out+=f"Greek {z['number']}:\n\n> {z['text'].strip()}\n\n"
    a=u['text'].index('Tyberium autem nepotem');z=u['text'].index('Tunc tamen licet');out+='Latin on both sides:\n\n> '+u['text'][a:z]+'\n\n'
    p=result['shared_transition_locator'];out+=f"Latin215 is followed directly by the Latin218 opening, before `Et tunc quidem in his`, paragraph `{p['stable_id']}`, Unicode paragraph coordinate {p['unit_offset']}, UTF-8 file byte {p['raw_byte']}, node `{p['text_node_path']}`, node coordinate {p['node_offset']}. No separate positive-length occurrence for216 or217 was found.\n\n"
    out+='A records both Latin identities as unavailable in this transcription, with independent Greek and contextual English and a cause-neutral note. B treats the opening reference to the succession omen at218 as compressed overlapping evidence for217; it must remain qualified and cannot create a second independent interval from the same occurrence. A is recommended because that reference concerns the particular succession omen already narrated, while217 makes a separate general statement of reliance on divination. This is a representation decision, not a judgement that the manuscript lost text. Both choices preserve every source character.\n'
    (d/'CASE_216_217.md').write_text(out,encoding='utf8',newline='\n')
    print(json.dumps(dict(Greek_individually_reviewed=sum(r['print_review_status']=='VISUALLY_REVIEWED' for r in rows),Latin_individually_reviewed=len(rows),pending=[r['number'] for r in rows if not r['candidate'].get('approved',False)],production_applied=False)))

if __name__=='__main__':main()
