const fs=require('fs'),path=require('path'),http=require('http');
const {chromium}=require('C:/Users/Pollard_R/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root=path.resolve(__dirname,'../..'),site='C:/Users/Pollard_R/AppData/Local/Temp/LatinJosephus-Whiston-Index-disposable-20261009';
const expected=JSON.parse(fs.readFileSync(path.join(__dirname,'CONTENTS_EXPECTATIONS.json'),'utf8')),existing=JSON.parse(fs.readFileSync(path.join(__dirname,'EXISTING_CONTENTS_EXPECTATIONS.json'),'utf8'));
const renderer=fs.readFileSync(path.join(site,'assets/js/renderTei.js'),'utf8');
const report={result:'RUNNING',site,checks:[],interactions:[],existing:[],screenshots:[],pageErrors:[],failedRequests:[]};
const capture=path.join(__dirname,'presentation-correction');
const save=()=>fs.writeFileSync(path.join(__dirname,'presentation-correction/CSS_SCOPE_QA.json'),JSON.stringify(report,null,2));
const server=http.createServer((req,res)=>{const u=new URL(req.url,'http://localhost');let target=path.resolve(site,'.'+decodeURIComponent(u.pathname));if(!target.startsWith(site.replaceAll('/',path.sep)+path.sep)){res.statusCode=403;res.end();return;}if(fs.existsSync(target)&&fs.statSync(target).isDirectory())target=path.join(target,'index.html');if(!fs.existsSync(target)){res.statusCode=404;res.end();return;}res.setHeader('Content-Type',({'.html':'text/html','.xml':'application/xml','.js':'text/javascript','.css':'text/css','.otf':'font/otf','.woff2':'font/woff2','.svg':'image/svg+xml','.png':'image/png'})[path.extname(target)]||'application/octet-stream');res.end(fs.readFileSync(target));});
(async()=>{
 await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin=`http://127.0.0.1:${server.address().port}`;const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'});const context=await browser.newContext({viewport:{width:1690,height:1100},deviceScaleFactor:1});
 await context.route('**/assets/js/renderTei.js',route=>route.fulfill({contentType:'text/javascript',body:renderer.replace('  bookTitle.innerText = activeWork.title;','  window.__toc={state:()=>({...state}),reload,assign:p=>Object.assign(state,p)};\n  bookTitle.innerText = activeWork.title;').replaceAll('setState(() => {','window.__tocPending = setState(() => {').replace('  reload().then(() => {','  reload().then(() => {\n    window.__tocReady=true;')}));
 const page=await context.newPage();page.on('pageerror',e=>report.pageErrors.push(String(e)));page.on('requestfailed',r=>report.failedRequests.push({url:r.url(),error:r.failure()?.errorText}));
 async function open(route){await page.goto(origin+route,{waitUntil:'load',timeout:60000});await page.waitForFunction(()=>window.__tocReady,{},{timeout:60000});await page.evaluate(()=>document.fonts.ready);}
 async function settle(){await page.evaluate(()=>window.__tocPending);}
 async function snap(name){await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:path.join(capture,name)});report.screenshots.push(name);}
 const cases=[['/antiquities/?book=3&view=contents','#latin .source-contents'],['/antiquities/?book=5&view=contents','#greek .source-contents'],['/bellum-judaicum/?book=1&view=contents&english=lodge1602','#english .source-contents'],['/antiquities/?book=3&chapter=1','#english tei-p'],['/antiquities/?book=3&chapter=1','#greek tei-p'],['/antiquities/?book=3&chapter=1','#latin tei-p'],['/deh/?book=1','#latin tei-p'],['/contra-apionem/?book=1','#english tei-p']];
 const oldCSS=fs.readFileSync(path.join(capture,'before-source/assets/css/tei.css'));const baseline={};
 for(const phase of ['before','after']){
  if(phase==='before')await context.route('**/assets/css/tei.css*',route=>route.fulfill({contentType:'text/css',body:oldCSS}));else await context.unroute('**/assets/css/tei.css*');
  for(const theme of ['light','dark'])for(const [route,selector] of cases){await open(route);await page.evaluate(t=>document.documentElement.dataset.theme=t,theme);await page.waitForTimeout(900);const style=await page.locator(selector).first().evaluate(x=>{const s=getComputedStyle(x);const base=Object.fromEntries(['fontFamily','fontSize','fontStyle','fontWeight','textAlign','textTransform','color','lineHeight','letterSpacing','wordSpacing'].map(k=>[k,s[k]]));base.sourceDescendants=[...x.querySelectorAll('tei-head,tei-p,tei-item,tei-supplied')].map(n=>{const c=getComputedStyle(n);return {tag:n.localName,text:n.textContent,fontFamily:c.fontFamily,fontSize:c.fontSize,fontStyle:c.fontStyle,textAlign:c.textAlign,color:c.color}});return base;});const key=theme+' '+route+' '+selector;if(phase==='before')baseline[key]=style;else{if(JSON.stringify(style)!==JSON.stringify(baseline[key])){fs.writeFileSync(path.join(capture,'CSS_DIFFERENCE.json'),JSON.stringify({key,before:baseline[key],after:style},null,2));throw Error('Out-of-scope typography changed '+key)};report.checks.push({theme,route,selector,styles:style,result:'PASS'});}}
 }
 if(report.pageErrors.length||report.failedRequests.length)throw Error('Browser errors');report.result='PASS';report.comparisons=report.checks.length;report.scope='Greek, Bamberg, Lodge and ordinary three-pane/DEH/Apion typography identical against pre-correction CSS';save();await browser.close();server.close();console.log('CSS_SCOPE_PASS',report.comparisons);
})().catch(e=>{report.result='FAIL';report.failure=String(e);save();console.error(e);server.close();process.exit(1)});
