const fs=require('fs'),path=require('path'),http=require('http');
const {chromium}=require('C:/Users/Pollard_R/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root=path.resolve(__dirname,'../..'),site='C:/Users/Pollard_R/AppData/Local/Temp/LatinJosephus-Whiston-Index-disposable-20261009';
const expected=JSON.parse(fs.readFileSync(path.join(__dirname,'CONTENTS_EXPECTATIONS.json'),'utf8')),existing=JSON.parse(fs.readFileSync(path.join(__dirname,'EXISTING_CONTENTS_EXPECTATIONS.json'),'utf8'));
const renderer=fs.readFileSync(path.join(site,'assets/js/renderTei.js'),'utf8');
const report={result:'RUNNING',site,checks:[],interactions:[],existing:[],screenshots:[],pageErrors:[],failedRequests:[]};
const save=()=>fs.writeFileSync(path.join(__dirname,'presentation-correction/BEFORE_STABLE_FAILURE.json'),JSON.stringify(report,null,2));
const server=http.createServer((req,res)=>{const u=new URL(req.url,'http://localhost');let target=path.resolve(site,'.'+decodeURIComponent(u.pathname));if(!target.startsWith(site.replaceAll('/',path.sep)+path.sep)){res.statusCode=403;res.end();return;}if(fs.existsSync(target)&&fs.statSync(target).isDirectory())target=path.join(target,'index.html');if(!fs.existsSync(target)){res.statusCode=404;res.end();return;}res.setHeader('Content-Type',({'.html':'text/html','.xml':'application/xml','.js':'text/javascript','.css':'text/css','.otf':'font/otf','.woff2':'font/woff2','.svg':'image/svg+xml','.png':'image/png'})[path.extname(target)]||'application/octet-stream');res.end(fs.readFileSync(target));});
(async()=>{
 await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin=`http://127.0.0.1:${server.address().port}`;const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'});const context=await browser.newContext({viewport:{width:1690,height:1100},deviceScaleFactor:1});
 await context.route('**/assets/js/renderTei.js',route=>route.fulfill({contentType:'text/javascript',body:renderer.replace('  bookTitle.innerText = activeWork.title;','  window.__toc={state:()=>({...state}),reload,assign:p=>Object.assign(state,p)};\n  bookTitle.innerText = activeWork.title;').replaceAll('setState(() => {','window.__tocPending = setState(() => {').replace('  reload().then(() => {','  reload().then(() => {\n    window.__tocReady=true;')}));
 const page=await context.newPage();page.on('pageerror',e=>report.pageErrors.push(String(e)));page.on('requestfailed',r=>report.failedRequests.push({url:r.url(),error:r.failure()?.errorText}));
 async function open(route){await page.goto(origin+route,{waitUntil:'load',timeout:60000});await page.waitForFunction(()=>window.__tocReady,{},{timeout:60000});await page.evaluate(()=>document.fonts.ready);}
 async function settle(){await page.evaluate(()=>window.__tocPending);}
 async function snap(name){await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:path.join(__dirname,name)});report.screenshots.push(name);}
 const original=path.join(__dirname,'presentation-correction/before-source');
 await context.route('**/assets/css/tei.css*',route=>route.fulfill({contentType:'text/css',body:fs.readFileSync(path.join(original,'assets/css/tei.css'))}));
 await context.route('**/assets/xml/source-contents.xml*',route=>route.fulfill({contentType:'application/xml',body:fs.readFileSync(path.join(original,'assets/xml/source-contents.xml'))}));
 await context.route('**/assets/xml/antiquities/paratext/whiston/*.xml*',route=>route.fulfill({contentType:'application/xml',body:fs.readFileSync(path.join(original,new URL(route.request().url()).pathname.replace(/^\/+/,'')))}));
 const beforeReport={result:'RUNNING',checks:[],screenshots:[]};
 for(const theme of ['light','dark'])for(const book of [1,3,5,12,20]){
  await open(`/antiquities/?book=${book}&view=contents`);await page.evaluate(t=>document.documentElement.dataset.theme=t,theme);await page.waitForTimeout(900);
  const data=await page.locator('#english .source-contents').evaluate(n=>({provenanceNoteBefore:!!n.querySelector(':scope > .source-contents-note'),provenanceNoteAfter:n.querySelectorAll('tei-div > tei-note[type="editorial"]').length,heading:n.querySelector('tei-item').textContent,entry:{textAlign:getComputedStyle(n.querySelector('tei-item')).textAlign,textTransform:getComputedStyle(n.querySelector('tei-item')).textTransform,fontFamily:getComputedStyle(n.querySelector('tei-item')).fontFamily},summary:{textAlign:getComputedStyle(n.querySelector('tei-div > tei-p')).textAlign,textTransform:getComputedStyle(n.querySelector('tei-div > tei-p')).textTransform}}));if(!data.provenanceNoteBefore||data.entry.textAlign!=='justify'||data.heading!==expected[book-1].headings[0])throw Error('Initial presentation snapshots not reproduced');beforeReport.checks.push({book,theme,...data});
  const name=`presentation-correction/BEFORE_STABLE_Whiston-${book}_${theme}.png`;await snap(name);beforeReport.screenshots.push(name);
  for(const chapter of book===3?[8,15]:book===5?[3]:[]){await page.locator(`#english tei-item[n="${chapter}"]`).scrollIntoViewIfNeeded();const name=`presentation-correction/BEFORE_STABLE_Whiston-${book}-${chapter}_${theme}.png`;await page.screenshot({path:path.join(__dirname,name)});beforeReport.screenshots.push(name);}
 }
 beforeReport.result='PASS';fs.writeFileSync(path.join(__dirname,'presentation-correction/BEFORE_STABLE_BROWSER_QA.json'),JSON.stringify(beforeReport,null,2));await browser.close();server.close();console.log('PRESENTATION_BEFORE_CAPTURE_PASS');
})().catch(e=>{report.result='FAIL';report.failure=String(e);save();console.error(e);server.close();process.exit(1)});
