"""Freeze the actual completed independent-work evidence; editorial completion is separate."""
from pathlib import Path
import json,hashlib,subprocess,shutil,sys,datetime
from mixed_mapper import Book,digest
P=Path(__file__).resolve().parent;W=P.parents[1];R=Path('C:/workspace/Antiquities-Niese-09-runtime-20261009');C=Path('C:/Users/Pollard_R/Git/LatinJosephus-v2-development')
def read(p):return json.loads(p.read_text(encoding='utf8'))
def write(p,v):p.write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n',encoding='utf8',newline='\n')
def git(*args,where=W):return subprocess.check_output(['git','--no-optional-locks',*args],cwd=where).decode().strip()
base=read(P/'BASELINE.json');ids=read(P/'EXECUTABLE_IDENTITIES.json');preservation=read(P/'SOURCE_PRESERVATION_QA.json');qa=read(P/'NEW_BOOK_BROWSER_QA.json');protected=read(P/'PROTECTED_BROWSER_QA.json');bellum=read(P/'PROTECTED_SOURCE_GATE_QA.json');inherited=read(P/'INHERITED_ISSUES_QA.json')
assert qa['result']==('PASS_INDEPENDENT_WORK_PROVISIONAL' if ids['pending'] else 'PASS_CERTIFIED')
assert protected['result']==bellum['result']==inherited['result']==preservation['result']=='PASS'
assert len(qa['actual_selector_events'])==291 and len(qa['traditional_ranges'])==68
assert not qa['errors'] and not qa['consoleErrors'] and not qa['networkFailures']
assert all(s['byte_exact_recovery'] and s['source_build_byte_equal'] for s in preservation['sources'].values())
assert preservation['reader_build_byte_equal'] and preservation['registry_build_byte_equal']
inherited['publicationSHA256']=digest(Path(inherited['publicationPath']).read_bytes());write(P/'INHERITED_ISSUES_QA.json',inherited)
tools={'Python':{'absolute_path':sys.executable,'version':sys.version,'sha256':digest(Path(sys.executable).read_bytes())},'Node':{'absolute_path':shutil.which('node'),'version':subprocess.check_output(['node','--version']).decode().strip()},'Git':{'absolute_path':shutil.which('git'),'version':git('--version')},'Chrome':{'absolute_path':'C:/Program Files/Google/Chrome/Application/chrome.exe','sha256':digest(Path('C:/Program Files/Google/Chrome/Application/chrome.exe').read_bytes())},'Playwright':{'absolute_package':'C:/Users/Pollard_R/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright','version':read(Path('C:/Users/Pollard_R/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/package.json'))['version']},'Docker':{'engine':'29.7.2','image':'ruby:3.3-bookworm','image_id':'sha256:dba270af6994f64e45ee3dd2b85225a2a0d01f29c04508c7a3c7c8dbf59d2a85'},'Bundler':{'version':'4.0.22','source':'build.sh and dependency log'}}
write(P/'EXECUTABLE_TOOLS.json',tools)
logdir=P/'build-logs';logdir.mkdir(exist_ok=True)
for name in ['jekyll.log','baseline-jekyll.log']:shutil.copyfile(R/'build'/name,logdir/name)
assets={}
for rel in preservation['only_production_paths_changed']:
    assets[rel]={'source_sha256':digest((W/rel).read_bytes()),'served_build_sha256':digest((R/'build/site'/rel).read_bytes()),'byte_equal':(W/rel).read_bytes()==(R/'build/site'/rel).read_bytes()}
assert all(v['byte_equal'] for v in assets.values())
write(P/'BUILD_RECORD.json',{'result':'PASS','frozen_baseline':base['base'],'full_build_implementation_commit':'ed61ef79cfa19a238ab16e89a99e5795d4224769','build_script_absolute':str(P/'build.sh'),'runtime':str(R),'source_mount_read_only':True,'baseline_from_git_archive':True,'implementation_and_baseline_Jekyll_builds':'SUCCESS_EXIT_0','static_refresh':[{'path':'assets/xml/antiquities/niese/book-09.json','reason':'Refine the IX.110 partial-correspondence notice without changing source intervals; ordinary unprocessed static JSON copied byte-for-byte after full build','source_commit':git('rev-parse','HEAD')}],'assets':assets,'log_hashes':{f.name:digest(f.read_bytes()) for f in logdir.iterdir()},'tool_identities':'EXECUTABLE_TOOLS.json','QA_origin':qa['origins'][0],'separate_profiles':[str(R/name) for name in ['profile-ix','profile-protected','profile-bellum','profile-inherited-issues']]})
method=[]
for rel in ['review/Antiquities_Niese_BookVIII_2026-10-08/SOURCE_AUTHORITY.md','review/Antiquities_Niese_BookX_2026-10-08/SOURCE_AUTHORITY.md','review/Antiquities_Niese_BookX_2026-10-08/mixed_mapper.py','review/Antiquities_Niese_Batch_08_10_2026-10-08/METHOD_SOURCE_MANIFEST.json','review/Antiquities_Niese_Implementation_08_10_2026-10-09/implement.py','review/Antiquities_Niese_Implementation_08_10_2026-10-09/browser-certify.cjs','review/Antiquities_Niese_Implementation_08_10_2026-10-09/established-regressions.test.cjs','review/Antiquities_Niese_Integration_08_10_2026-10-09/REPORT.md']:
    method.append({'absolute_path':str(W/rel),'sha256':digest((W/rel).read_bytes()),'Git_base_blob_id':git('rev-parse',base['base']+':'+rel),'role':'Pinned accepted methodological/control evidence'})
method.append({'absolute_path':str(P/'mixed_mapper.py'),'sha256':digest((P/'mixed_mapper.py').read_bytes()),'role':'Local derived mapper: exact IX placeholders and terminal subscription exclusion; 16 fixtures and independent real-source locators verified'})
write(P/'METHOD_SOURCE_MANIFEST.json',method)
summary={'book':9,'branch':git('branch','--show-current'),'frozen_base':base['base'],'canonical_initial_HEAD':base['canonical_initial_HEAD'],'canonical_latest_HEAD':git('rev-parse','HEAD',where=C),'canonical_advance':git('rev-parse','HEAD',where=C)!=base['canonical_initial_HEAD'],'canonical_status':git('status','--porcelain',where=C),'worktree':str(W),'review':str(P),'runtime':str(R),'implementation_HEAD_before_certification_commit':git('rev-parse','HEAD'),'expected_identities':291,'represented_Latin_candidates':232,'inherited_Latin_starts':46,'proposed_Latin_milestones':186,'applied_Latin_milestones':185 if ids['pending'] else 186,'actual_Latin_source_starts':preservation['sources']['Latin']['actual_starts'],'Latin_nonempty_reader_intervals':sum(e['Latin']=='REPRESENTED' for e in qa['actual_selector_events']),'Greek_nonempty_reader_intervals':sum(e['Greek']=='REPRESENTED' for e in qa['actual_selector_events']),'whole_section_unavailable':59,'unavailable_span':[51,109],'partial_surviving_sections':[110],'suppressed_IX_inherited_labels':0,'Greek_marker_additions':[1],'Greek_marker_moves':[181,216]+([240] if not ids['pending'] and read(P/'EDITORIAL_DECISIONS.json')['240']['choice']=='A' else []),'pending_editorial_decisions':ids['pending'],'adjacent_extents_held':[239,240] if ids['pending'] else [],'published_selection_baseline':3157,'local_added_selectable_identities':291,'local_selectable_total':3448,'publication_updated':False,'all_other_books_unchanged':True,'source_recovery':'BYTE_EXACT','new_book_reader_QA':qa['result'],'all_actual_IX_selector_events':291,'actual_IX_chapter_ranges':sum(r['kind']=='chapters' for r in qa['traditional_ranges']),'actual_IX_subchapter_ranges':sum(r['kind']=='subchapters' for r in qa['traditional_ranges']),'protected_Niese_selections':sum(x['identities'] for x in protected['antiquities']['niese']),'protected_traditional_ranges':sum(x['identities'] for x in protected['antiquities']['traditional']),'protected_Bamberg_ranges':sum(x['identities'] for x in protected['antiquities']['bamberg']),'protected_alignment_units':sum(x['identities'] for x in protected['antiquities']['alignment']),'protected_cross_work_books':len(protected['crossWorks']),'Bellum_witness_range_comparisons':sum(x['ranges'] for x in bellum['checks']),'QA_origin':qa['origins'][0],'technical_independent_work_complete':True,'editorial_completion':'PROVISIONAL_PENDING_240' if ids['pending'] else 'COMPLETE','ready_for_integration':not bool(ids['pending']),'no_merge_push_deploy':True,'recorded_UTC':datetime.datetime.now(datetime.UTC).isoformat()}
write(P/'CERTIFICATION.json',summary)
commits=git('log','--reverse','--format=%H %s',base['base']+'..HEAD').splitlines()
report=f'''# Antiquities IX — local independent-work handoff

Status: **PROVISIONAL — one editorial decision pending at IX.240**. All independent scholarly review, local implementation and technical reader work is complete. This is not a readiness declaration for integration. No merge, push, preview update or deployment occurred.

The frozen base is `{base['base']}`. Canonical began at that commit and was clean; its latest recorded HEAD is `{summary['canonical_latest_HEAD']}`, with no later advance and no canonical working-file changes. The isolated branch is `{summary['branch']}` at `{W}`. Evidence is in `{P}`; disposable builds, logs and browser profiles are in `{R}`. Actual IX browser origin was `{summary['QA_origin']}`; protected comparison servers used separate free ports. All browser profiles belong to this assignment.

## Coverage and implementation

Niese II's independently examined opening and ending establish1–291. All291 printed starts and all232 surviving Latin candidates were individually reviewed. The actual Greek, Latin and English XML each omit51–109 behind their preserved editorial placeholder;59 identities therefore have explicit per-witness unavailability. This establishes an omission in these files, not its physical cause or a claim about the whole Latin tradition. IX.110 preserves only Jehu's concluding reply; its partial-survival notice is visible without reconstructed wording.

The Latin plan contains46 independently verified retained visible starts and186 additional milestones.185 are applied;240 is held. There are231 physical Latin source starts, of which230 render nonempty certified intervals while239–240 remain explicitly provisional. The232 surviving candidate intervals form the reviewed complete narrative partition. These counts are separate from291 selectable IX identities. Published coverage remains3157; this local build adds291 provisional selectable identities, giving3448 local selections. It does not add291 Latin text intervals.

Greek edits are explicitly limited to opening `[1]`, move181 before `τρία βέλη`, and move216 before `τὸν αὐτὸν δὲ τρόπον`. The latter two were independently checked in Loeb. No other source words, punctuation, whitespace, notes, IDs, sameAs, paragraph numbering, source contents, traditional/Bamberg divisions or English source bytes change. IX requires no inherited-label executable override. The reader changes are the IX registry path and two opt-in generic data behaviors described in SHARED_SUPPORT.md; display-settings.html is unchanged.

Exact inversion removes only added Latin milestones and reverses the authorized Greek marker edits, recovering the same frozen working-tree bytes and SHA-256 hashes used by the locators. Greek and Latin coordinate streams exclude paratext, num labels, notes, apparatus and the exact omission placeholders. The terminal `explicit liber nonus` remains in the source/display extent but is separately excluded as a subscription label. No XML-wide normalization or reserialization is used.

## Actual reader evidence

NEW_BOOK_BROWSER_QA.json records all291 real selector events, exact Greek/Latin extents, Whiston broader context, every unavailable/pending state, no duplicate executable or DOM IDs, and no unresolved IX pane links. Actual Chapter/Subchapter events cover{summary['actual_IX_chapter_ranges']} chapters and{summary['actual_IX_subchapter_ranges']} subchapters, compared to the pinned complete baseline range projections. The inherited traditional unavailability is preserved rather than hidden. Deep links, previous/next endpoints, history, reload, English/Greek pane switching, mandatory Latin-pane behavior, and light/dark theme application pass. Production code was independently exercised at openings, omission edges,110,181,216,239–240 and291. The two110 screenshots were visually inspected: notices, text, controls and brand images render correctly in both themes.

Protected comparisons preserve{summary['protected_Niese_selections']} existing Antiquities Niese selections, all{summary['protected_traditional_ranges']} traditional ranges,{summary['protected_Bamberg_ranges']} Bamberg ranges,{summary['protected_alignment_units']} Alignment units and source contents across the preface/I–XX. Greek/Latin marker differences are stripped solely for comparison of authorized IX/VIII/X edits; all other source behavior and order remains unchanged. Cross-work checks cover{summary['protected_cross_work_books']} books of Bellum, Contra Apionem and DEH. The separate Bellum gate compares{summary['Bellum_witness_range_comparisons']} Whiston/Lodge book, Niese, chapter and Alignment ranges. Lodge note toggling, source switching and reload pass.

Accepted controls include all four inherited-label exceptions, VIII.367–369 and X.101–102,108–109,150–151,276–277. Greek/English remain independently available at X.108. INHERITED_ISSUES_QA.json precisely reproduces only the documented three apparatus links/two malformed Book-I targets and unsupported I.1 error, and verifies supported I.27. Passing gates report zero unexpected script, console or network diagnostics. Early sandbox loopback denial and two corrected harness assumptions are retained as historical attempts, not classified as reader defects. Local SVG MIME serving was corrected during screenshot QA; no production image change was needed.

## Decision required and closure path

DECISION_240.md links Niese printed317/PDF325 and Loeb printed126/PDF142. Each numeral identifies a line shared by two plausible clause starts. **A, recommended:** Greek240 before `ἔσται δ᾽ οὐδεὶς βουλησόμενος`, Latin before `et nullus hanc uoluntatem habebit`, keeping refusal and explanation together. **B:** retain Greek before `σώζειν γὰρ`, Latin before `dum animas suas`, assigning the refusal to239. Both exact alternatives, raw-byte/Unicode locators and239/240 extents are in DECISION_240_ALTERNATIVES.json. No user decision has been received.

After adjudication, record the user's choice in EDITORIAL_DECISIONS.json, rebuild the register, apply the remaining Latin milestone and the Greek240 move only if A is chosen, clear the temporary239–240 notices, and rerun the affected reader/preservation checks. Then commit the adjudication, final corpus operation and certification separately. The existing independent-work evidence remains valid; integration must still reconcile this frozen branch with then-current canonical.

## Scoped local commits so far

'''+'\n'.join('- `'+c[:40]+'` '+c[41:] for c in commits)+'''\n\nThe per-book QA/evidence commit follows these implementation commits. Its final hash and clean status are reported in the handoff response, avoiding a self-referential commit ID inside its own committed file. FILE_MANIFEST.json contains exact changed paths, frozen-input hashes, served-asset hashes and review-file hashes; the manifest excludes itself from self-hashing.\n'''
(P/'REPORT.md').write_text(report,encoding='utf8',newline='\n')
manifest={'frozen_base':base['base'],'production_changes':assets,'Git_changed_files':sorted(set(git('diff','--name-only',base['base']).splitlines()+git('ls-files','--others','--exclude-standard').splitlines())),'review_files':[{'absolute_path':str(f),'relative_path':str(f.relative_to(W)).replace('\\','/'),'bytes':f.stat().st_size,'sha256':digest(f.read_bytes())} for f in sorted(P.rglob('*')) if f.is_file() and '__pycache__' not in f.parts and f.name!='FILE_MANIFEST.json'],'self_hash_exclusions':['FILE_MANIFEST.json']}
write(P/'FILE_MANIFEST.json',manifest)
print(json.dumps(summary,ensure_ascii=False,indent=2))
