"""Record the direct human adjudication and revalidate its frozen-source cut."""
import sys
sys.path.insert(0,str(__import__('pathlib').Path(__file__).resolve().parents[1]/'Antiquities_Niese_Batch_12_13_2026-10-09'))
from record_review import *
d=packet(13);bs=books(13);l=bs['Latin']
decision=json.loads((d/'DECISION_XIII_213_216.json').read_text(encoding='utf8'))
assert {k:digest(v.raw) for k,v in bs.items()}==decision['input_hashes']
cut=decision['alternative_exact_extents']['B']['214']['start'];independent_node(l,cut)
assert l.locate(cut['book_offset'])==cut and l.raw[cut['raw_byte']:].startswith(b'Itaque iudaei feliciter')
choices=json.loads((d/'LATIN_REVIEW_CHOICES.json').read_text(encoding='utf8'))
notices={
 '212':'The appended documentary dating formula, “in mutuis documentis publicisque monumentis primi anni simonis benefactoris et iudaeorum principis scriptum est.”, survives here in latin-book13-num208 and corresponds to Greek XIII.214. Its continuation, the prosperity-and-victories statement, is displayed in the Latin interval for XIII.214. This partial correspondence is distributed between two physical intervals; the transmitted wording and sequence are preserved, and the cause of the altered correspondence is unknown.',
 '213':'No independent Latin interval. The full reviewed Latin context has no identifiable counterpart of this section\'s separate account of Simon\'s appointment as high priest, liberation from Macedonian tribute and the 170-year chronology. The documentary dating formula within XIII.212 corresponds to Greek XIII.214 and does not supply this liberation account. The earlier military appointment in latin-book13-num201 is a different account. Greek and English remain independently accessible; no cause, physical loss or tradition-wide absence is inferred.',
 '214':'Partial correspondence distributed between two physical intervals. The documentary dating formula corresponding to Greek XIII.214 survives earlier within the Latin interval for XIII.212, in latin-book13-num208, at “in mutuis documentis publicisque monumentis primi anni simonis benefactoris et iudaeorum principis scriptum est.” This interval begins with the ensuing prosperity-and-victories statement, “Itaque iudaei feliciter aduersarios uicinos superauerunt,”. The earlier dating material is not absent. The wording and existing sequence are preserved; the cause of the altered correspondence is unknown.',
 '216':'No independent Latin interval. The full reviewed Latin context has no identifiable counterpart of this section\'s assembly persuasion and warnings about the former garrison and possible foreign restoration. The neighbouring collective demolition survives in XIII.217; it is not reassigned to manufacture an interval here. Greek and English remain independently accessible; no cause, physical loss or tradition-wide absence is inferred.'
}
choices['212'].update({'assessment':'Monument summary and Jonathan\'s four-year high priesthood continue through the appended documentary dating formula; the latter corresponds to Greek214 and continues as the prosperity statement in physical interval214. The full transmitted sentence is retained under212, as approved in B.','limits':'Partial correspondence with Greek214 is distributed between physical intervals212 and214. No earlier dating material is absent or reconstructed.','notice':notices['212'],'correspondence':'INCLUDES_DISPLACED_214_DATING','status':'USER_APPROVED'})
choices['214']={'phrase':'Itaque iudaei feliciter','paragraph':'latin-book13-num213','assessment':'The ensuing prosperity-and-victories statement corresponds to the surviving ending of Greek214. The documentary dating formula survives earlier within interval212, with a reciprocal notice. The inherited visible [VI.vii.213] label and paragraph identity are retained but its executable213 claim is suppressed.','limits':'Partial correspondence distributed between two physical intervals: documentary dating in212 and ensuing prosperity and victories in214. Cause unknown; no reconstructed transition.','status':'USER_APPROVED','notice':notices['214'],'correspondence':'PARTIAL_DISTRIBUTED_WITH_212'}
for n in ['213','216']:
 assert choices[n]['phrase'] is None
 choices[n].update({'status':'USER_APPROVED','limits':'No independent Latin interval under the approved B representation and individual full-source review. No neighbouring material is assigned to create one; cause remains unknown.','notice':notices[n]})
choices['217']['limits']='The assembly persuasion and warnings of216 have no independently identifiable counterpart in the reviewed context. Collective demolition survives in217, and the closing Simon formula resumes within218; no neighbouring interval is manufactured for216.'
save(d/'LATIN_REVIEW_CHOICES.json',choices);apply(13)
rows=json.loads((d/'BOUNDARIES.json').read_text(encoding='utf8'));assert rows[213]['Latin']['locator']==cut
assert rows[211]['Latin']['end_book_offset']==cut['book_offset'] and rows[213]['Latin']['end_book_offset']==rows[214]['Latin']['locator']['book_offset']
assert all(r['implementation_approved'] for r in rows)
record={'date':'2026-10-09','authority':'Direct human approval in this chat: Approve B as described in the updated decision packet','adopted_alternative':'B','approved_cut':cut,'source_condition':'Validated against the same frozen source hash and independently against XML text/tail and raw UTF-8 bytes','approved_notices':notices,'statuses':{'213':'NO_INDEPENDENT_LATIN_INTERVAL; no identifiable separate liberation-account counterpart in full reviewed transcription','214':'PARTIAL_DISTRIBUTED_WITH_212; start immediately before Itaque iudaei feliciter','215':'PRESENT; unchanged independently reviewed interval','216':'NO_INDEPENDENT_LATIN_INTERVAL; no identifiable assembly/warning counterpart in full reviewed transcription'},'preservation':'No wording, punctuation, whitespace, paragraph IDs, divisions, inherited labels or witness order changed; English and independently established Greek boundaries retained','alternatives_retained':'DECISION_XIII_213_216.json alternative_exact_extents preserves A and B; recommendation_history preserves the source-first A proposal and subsequent reader/English-context reason for B','affected_extents':[{'niese':r['niese'],'start':r['Latin']['locator'],'end_book_offset':r['Latin'].get('end_book_offset'),'interval':r['Latin'].get('interval') if r['Latin']['locator'] else None,'status':r['editorial_status']} for r in rows[211:217]],'pending_editorial_decisions':[]}
save(d/'EDITORIAL_DECISIONS.json',record)
decision['status']='ADOPTED_USER_APPROVED_B';decision['adjudication']=record;save(d/'DECISION_XIII_213_216.json',decision)
with (d/'DECISION_XIII_213_216.md').open('a',encoding='utf8') as f:f.write('\n## Closed adjudication — 2026-10-09\n\nThe user approved B as described in this updated packet: Latin214 begins immediately before `Itaque iudaei feliciter`, at the validated frozen-source locator. Partial correspondence is distributed between physical212 and214; the documentary dating formula remains in212, and the prosperity-and-victories statement begins214. Reciprocal reader and audit notices identify both locations. Sections213 and216 retain their individual full-source absence-of-identifiable-correspondence assessments without manufactured intervals. Section215 remains present and unchanged. Both alternatives and the reason for the changed recommendation remain above and in the JSON. EDITORIAL_DECISIONS.json records the adopted cut, notices and recomputed212–217 extents. No editorial decisions remain pending.\n')
print('Book XIII B adopted; all433 representations approved; physical intervals431; pending0')
