import sys
sys.path.insert(0,str(__import__('pathlib').Path(__file__).resolve().parents[1]/'Antiquities_Niese_Batch_12_13_2026-10-09'))
from record_review import *
d=packet(13); bs=books(13); rows=json.loads((d/'CANDIDATE_REGISTER.json').read_text(encoding='utf8')); c=json.loads((d/'LATIN_REVIEW_CHOICES.json').read_text(encoding='utf8')); o=json.loads((d/'PRINT_OBSERVATIONS.json').read_text(encoding='utf8'))
for n,assessment in [(213,'Complete reviewed Latin paragraphs 208,213,218 contain no identifiable account of Simon being appointed high priest, freeing the people from Macedonian tribute, or the 170-year Seleucid chronology.'),(216,'Complete reviewed Latin paragraphs 208,213,218 contain no identifiable account of the assembly persuasion and warnings about the former garrison and possible foreign restoration; the collective demolition survives at 217.')]:
 c[str(n)]={'phrase':None,'assessment':assessment,'limits':'No independent Latin interval proposed; no claim about physical loss or the entire Latin tradition. Awaiting editorial approval.','status':'PENDING_USER_DECISION','correspondence':'no-identifiable-correspondence-in-reviewed-transcription'}
 o[str(n)]={'edition':'Niese III, 1892','printed_page':190 if n==213 else 191,'PDF_page':262 if n==213 else 263,'image':f'evidence/Niese/page-{262 if n==213 else 263}.png','observed_numeral_position':'Left margin at division 7, Σίμων δὲ.' if n==213 else 'Right margin beside the preceding temple-height clause; καὶ δὴ follows.','word_boundary_status':'XML_WORD_START_CONFIRMED_FROM_PRINT','editorial_word_choice':'Keep the printed and XML Greek start.'}
for n in [214]: c[str(n)]['status']='PENDING_USER_DECISION'
save(d/'LATIN_REVIEW_CHOICES.json',c);save(d/'PRINT_OBSERVATIONS.json',o);apply(13)
rows=json.loads((d/'BOUNDARIES.json').read_text(encoding='utf8'))
units=[u for u in bs['Latin'].units if u['id'] in ['latin-book13-num208','latin-book13-num213','latin-book13-num218']]
save(d/'DECISION_XIII_213_216.json',{'book':13,'status':'PENDING_USER_DECISION','input_hashes':{k:digest(v.raw) for k,v in bs.items()},'Greek_208_219':[{'niese':r['niese'],'text':r['Greek']['section'],'locator':r['Greek']['locator']} for r in rows[207:219]],'Latin_complete_context':[{'paragraph':u['id'],'text':u['text'],'unit_hash':u['raw_hash']} for u in units],'proposed_212_219':[r for r in rows[211:219]]})
md='# Decision required: XIII.213, 214 and 216\n\nNiese III (1892), printed pp.190–191, PDF262–263: [213–214](evidence/Niese/page-262.png), [215–218](evidence/Niese/page-263.png). Greek213 describes Simon’s appointment, freedom from Macedonian tribute and the 170-year chronology. Greek214 gives the first-year dating formula, then prosperity. Greek216 gives an assembly persuasion and warnings about the former garrison and foreign restoration. All Latin paragraphs208,213,218 and Greek208–219 were reviewed. Cause of missing correspondence remains unknown; no physical-loss or tradition-wide claim is proposed.\n\n**A — recommended.** No independent Latin interval for213 or216. Preserve Greek/English addressability and display explicit contextual absence notices. Latin212 ends after `et de labore quidem mortis eius `; Latin214 starts `in mutuis documentis publicisque monumentis primi anni simonis benefactoris et iudaeorum principis scriptum est.` in paragraph208. It continues across preserved visible label213 into `Itaque iudaei feliciter aduersarios uicinos superauerunt,` (the prosperity ending of Greek214), and ends before `cum simon gazara ciuitatem` (215). Qualify214 as reordered and syntactically attached to Jonathan’s death in this transcription; give212 a reciprocal notice. Latin215 ends before `quo multitudo cunctique ingressi` (217);216 gets no manufactured cut. Keep all words and order.\n\n**B.** Keep the entire death-and-dating sentence under212, and start214 at `Itaque iudaei feliciter` in paragraph213, with notices that214’s dating formula survives earlier within212. The disposition of213/216 remains as in A. This keeps the Latin sentence whole but leaves the principal dating counterpart outside214’s own interval.\n\nThe complete extracts and exact proposed source locators are in DECISION_XIII_213_216.json. No source changes have been applied.\n\n'
for r in rows[211:219]:md+=f'Greek {r["niese"]}: {r["Greek"]["section"].strip()}\n\n'
for u in units:md+=f'Latin {u["id"]} (complete):\n\n> {u["text"].strip()}\n\n'
(d/'DECISION_XIII_213_216.md').write_text(md,encoding='utf8')
