import sys
sys.path.insert(0,str(__import__('pathlib').Path(__file__).resolve().parents[1]/'Antiquities_Niese_Batch_12_13_2026-10-09'))
from prepare_review import *
d=packet(13);bs=books(13);p=d/'DECISION_XIII_213_216.json';x=json.loads(p.read_text(encoding='utf8'))
x['English_context_consequences']={'A':{'contextTarget':'latin-book13-num208','English_paragraph':'english-book13-num208','principal_214_dating_and_prosperity_in_context':False,'explanation':'The inherited reader uses the physical Latin start paragraph. English208 ends with Jonathan\'s death and contains no dating formula; the actual 214 counterpart remains in preserved English213. No English re-alignment or source rewriting is proposed.'},'B':{'contextTarget':'latin-book13-num213','English_paragraph':'english-book13-num213','principal_214_dating_and_prosperity_in_context':True,'explanation':'The surviving prosperity clause starts in Latin213, so the unchanged reader shows the preserved English213 context containing the dating formula and prosperity. Latin dating remains earlier within 212, with reciprocal notices.'}}
x['English_complete_context']=[{'paragraph':u['id'],'sameAs':u['element'].get('sameAs'),'text':u['text'],'unit_hash':u['raw_hash']} for u in bs['English'].units if u['id'] in ['english-book13-num208','english-book13-num213','english-book13-num218']]
x['expanded_absence_context']=[{'paragraph':u['id'],'text':u['text'],'unit_hash':u['raw_hash']} for u in bs['Latin'].units if u['id'] in ['latin-book13-num187','latin-book13-num191','latin-book13-num194','latin-book13-num201','latin-book13-num203']]
x['expanded_absence_assessment']='The preceding leadership appointment in paragraph201 grants ducis dignitatem, matching Greek201 military leadership; it does not supply Greek213 high-priest appointment, release from Macedonian tribute or the 170-year chronology. All preceding paragraphs187–203 and complete208,213,218 have now been explicitly included in contextual evidence. No physical-loss or tradition-wide inference is made.'
x['recommendation_history']=[{'recommendation':'A','basis':'First identifiable dating counterpart assigned to214, with syntactic qualification; retained as the original proposal.'},{'recommendation':'B','basis':'Subsequent actual reader/Whiston-context review: preserve the full Latin sentence and correct existing broader English214 context, with displaced dating notices at212/214.'}]
x['current_recommendation']='B';save(p,x)
md=d/'DECISION_XIII_213_216.md';s=md.read_text(encoding='utf8').replace('**A — recommended.**','**A — original recommendation, superseded by the reader finding below.**');s+='''
## Updated recommendation: B

The actual Whiston source and existing reader context behavior were subsequently checked. A's physical Latin start is in paragraph208, so its English pane would show English208, ending with Jonathan's death and containing neither the dating formula nor prosperity of214. The actual English counterpart remains in preserved paragraph213. B starts214 at `Itaque iudaei feliciter`, in paragraph213, so the unchanged reader shows English213, which includes the full dating formula, prosperity, and adjoining context. This avoids an English alignment change while preserving the full Latin sentence. Both exact alternative cuts and neighbouring extents remain in the JSON.

I now recommend **B**: no independent Latin intervals for213 and216; Latin214 starts `Itaque iudaei feliciter`. Qualify214 as partial at its opening, with its dating formula displaced earlier within212 at `in mutuis documentis publicisque monumentis primi anni simonis benefactoris et iudaeorum principis scriptum est.` Provide a reciprocal212 notice giving the actual paragraph208 location, and qualify both as adapted syntax. Greek/English213 and216 stay independently accessible. Cause of missing correspondence remains unknown. The surviving217 demolition and resumed217 closing within218 remain preserved and qualified separately.

The wider preceding Latin187–203 was explicitly re-examined for the absence assessment: paragraph201 grants military leadership (`ducis ... dignitatem`), not the high-priest appointment, Macedonian tribute release or170-year chronology of Greek213. Complete wider Latin and English context is appended in the JSON. The recommendation history remains recorded; no pending representation has been implemented.
''';md.write_text(s,encoding='utf8')
print('Recorded exact English context consequences; current XIII recommendation B')
