const fs=require('fs'),path=require('path'),http=require('http'),crypto=require('crypto');
const {chromium}=require('C:/Program Files/WindowsApps/OpenAI.CodexPrimaryRuntime.v26-1007-641-0_26.1007.641.0_x64__3k8sg7r9htsxt/dependencies/node/node_modules/playwright');
const P=__dirname,root=path.resolve(P,'../..'),runtime='C:/workspace/Antiquities-Niese-Proem-runtime-20261010';
const norm=s=>s.replace(/\s+/g,' ').trim(),sha=x=>crypto.createHash('sha256').update(x).digest('hex');
// Read-only observation hooks follow the established published reader QA method.
// No hook changes a production selection, span or source file.
function narrative(node){if(!node)return '';const c=node.cloneNode(true);c.querySelectorAll('tei-num,tei-milestone,tei-note,tei-app,tei-rdg,.niese-context-note,.niese-correspondence-note,.structural-unavailable,.niese-source-passage-label').forEach(n=>n.remove());return [...(c.matches?.('tei-p')?[c]:[]),...c.querySelectorAll('tei-p')].filter(p=>!p.closest('tei-div2[n="0"]')).map(p=>p.textContent).join('');}
function instrument(s){s=s.replace('  bookTitle.innerText = activeWork.title;',`  window.__qa={getState:()=>({...state}),getData:()=>fullData,view:()=>viewData,antiquitiesNieseStartEntries,antiquitiesNieseExactView,traditionalRows,bambergRows,traditionalRangeView,traditionalPoint,milestoneChapterNumbers,milestoneChapterView,fixtureEnd:(n,target)=>{nieseIdentityRegistry().sections.find(s=>s.number===n).Latin.endTarget=target;}};\n  bookTitle.innerText = activeWork.title;`);s=s.replace('    syncNavigationControls();','    syncNavigationControls(); window.__qaRenderedState={...state};');return s.replace('  reload().then(() => {','  reload().then(() => { window.__qaReady=true; document.querySelector("#collapse-settings")?.classList.add("show");');}
function serve(site){return http.createServer((req,res)=>{let f=path.resolve(site,'.'+decodeURIComponent(new URL(req.url,'http://localhost').pathname));if(!f.startsWith(path.resolve(site)+path.sep)){res.statusCode=403;return res.end();}if(fs.existsSync(f)&&fs.statSync(f).isDirectory())f=path.join(f,'index.html');if(!fs.existsSync(f)){res.statusCode=404;return res.end();}let raw=fs.readFileSync(f);if(f.endsWith('renderTei.js'))raw=Buffer.from(instrument(raw.toString()));res.setHeader('Content-Type',f.endsWith('.xml')?'application/xml':f.endsWith('.json')?'application/json':f.endsWith('.js')?'text/javascript':f.endsWith('.html')?'text/html':f.endsWith('.css')?'text/css':f.endsWith('.svg')?'image/svg+xml':f.endsWith('.png')?'image/png':f.endsWith('.jpg')?'image/jpeg':'application/octet-stream');res.end(raw);});}
async function session(mode){const site=mode==='baseline'?path.join(runtime,'baseline-site'):JSON.parse(fs.readFileSync(path.join(P,'CANDIDATE_BUILD.json'))).site,server=serve(site);await new Promise((r,j)=>{server.once('error',j);server.listen(mode==='baseline'?8922:8920,'127.0.0.1',r);});const context=await chromium.launchPersistentContext(path.join(runtime,'browser-'+mode),{headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push({kind:'page',message:String(e)}));page.on('console',m=>{if(m.type()==='error')errors.push({kind:'console',message:m.text()});});page.on('requestfailed',r=>errors.push({kind:'request',url:r.url(),message:r.failure()?.errorText}));page.on('response',r=>{if(r.status()>=400)errors.push({kind:'HTTP',url:r.url(),status:r.status()});});
async function open(query,work='antiquities'){await page.goto('http://127.0.0.1:'+server.address().port+'/'+work+'/?'+query,{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>window.__qaReady,null,{timeout:60000});}
async function snapshot(){return page.evaluate(code=>{const text=eval('('+code+')'),ids=[...document.querySelectorAll('[id]')].map(n=>n.id);return {paneDOM:Object.fromEntries(['latin','greek','english'].map(l=>[l,document.querySelector('#'+l)?.innerHTML.replaceAll(location.origin,'LOCAL_ORIGIN')||null])),languages:Object.fromEntries(['Latin','Greek','English'].map(l=>[l,text(document.querySelector('#'+l.toLowerCase()))])),duplicates:ids.filter((id,i)=>ids.indexOf(id)!==i),note:document.querySelector('#latin .niese-correspondence-note')?.textContent||null,EnglishContext:!!document.querySelector('#english .niese-context-note'),unavailable:document.querySelector('#latin .structural-unavailable')?.textContent||null,state:window.__qa.getState(),sourceIDs:['latin','greek','english'].map(l=>[l,[...document.querySelectorAll('#'+l+' tei-p')].map(n=>[n.id,n.getAttribute('sameas')])])};},narrative.toString());}
async function select(n){await page.evaluate(async n=>{const menu=document.querySelector('#niese-selector');menu.value=String(n);menu.dispatchEvent(new Event('change',{bubbles:true}));const start=Date.now();await new Promise((resolve,reject)=>{const check=()=>{if(window.__qaRenderedState?.nieseNum===String(n)&&['latin','greek','english'].every(l=>document.querySelector(`#${l} [n="${n}"][type^="niese-"]`)))return resolve();if(Date.now()-start>30000)return reject(Error('All panes did not render '+n));setTimeout(check,5);};check();});},n);}
return {site,page,context,errors,open,snapshot,select,close:async()=>{await context.close();await new Promise(r=>server.close(r));}};}
module.exports={fs,path,P,root,runtime,norm,sha,narrative,session};
