const {fs,path,P,norm,sha,narrative,session}=require('./browser_common.cjs');
async function main(){const mode=process.argv[2]||'baseline',s=await session(mode),r={mode,scope:'ALL_ACTUAL_BASELINE_NIESE_IDENTITIES_AND_BOOKXX_CONTAINING_VIEWS',started:new Date().toISOString(),status:'RUNNING',books:[],selections:[],views:[],errors:s.errors},base=mode==='baseline'?null:JSON.parse(fs.readFileSync(path.join(P,'BASELINE_PROTECTED_BROWSER.json')));
 r.sourceBuild=mode==='baseline'?'4f88fc1483ec14d418c678004e13bc2b6741a2b7':JSON.parse(fs.readFileSync(path.join(P,'CANDIDATE_BUILD.json'))).source_commit;
try{
 const controls=JSON.parse(fs.readFileSync(path.join(P,'STRUCTURAL_CONTROLS.json')));
 await s.open('book=20');for(const l of ['greek','english'])await s.page.check('#'+l+'-pane-select');
 const census=await s.page.evaluate(()=>({alignment:[...document.querySelector('#section-selector').options].filter(o=>o.value).map(o=>o.value),legacy:window.__qa.milestoneChapterNumbers().filter(n=>Number(n)>0),traditional:window.__qa.traditionalRows('chapter').length,subchapters:window.__qa.traditionalRows('subchapter').length,bamberg:window.__qa.bambergRows().length}));r.XXcensus=census;
 r.XXlegacy=await s.page.evaluate(code=>{const q=window.__qa,text=eval('('+code+')'),d=q.getData();return q.milestoneChapterNumbers().filter(n=>Number(n)>0).map(n=>({number:n,languages:Object.fromEntries(['Latin','Greek','English'].map(l=>[l,text(q.milestoneChapterView(l,d[l],n,true))]))}));},narrative.toString());
 if(base&&JSON.stringify(r.XXlegacy)!==JSON.stringify(base.XXlegacy))throw Error('LegacyXX endpoints changed');
 const views=[{id:'XX-book',query:'book=20'},{id:'XX-contents',query:'book=20&view=contents'},...census.alignment.map(n=>({id:'XX-alignment-'+n,query:'book=20&unit='+n})),...controls.filter(c=>['chapter','subchapter','bamberg'].includes(c.scheme)).map(c=>({id:c.id,query:'book=20&'+(c.scheme==='bamberg'?'bamberg='+Number(c.id.split('-row')[1]):'chapter='+c.chapter+(c.scheme==='subchapter'?'&subchapter='+c.subchapter:''))}))];
 for(const v of views){await s.open(v.query);const a=await s.snapshot(),row={...v,languages:Object.fromEntries(Object.entries(a.languages).map(([l,t])=>[l,sha(norm(t))])),duplicates:a.duplicates,state:a.state};if(base){const b=base.views.find(b=>b.id===v.id);if(JSON.stringify(row.languages)!==JSON.stringify(b.languages)||JSON.stringify(row.duplicates)!==JSON.stringify(b.duplicates))throw Error('Containing view difference '+v.id);}r.views.push(row);}
 console.log('XX containing views',r.views.length);
 // Discover actual support from the live immutable reader, never a presumed count.
 const actualBooks=[];
 if(base)actualBooks.push(...base.books.map(b=>b.book));else for(let b=1;b<=20;b++){await s.open('book='+b);const m=await s.page.locator('#niese-selector').evaluate(n=>[...n.options].filter(o=>o.value).map(o=>Number(o.value)));if(m.length)actualBooks.push(b);}
 for(const b of actualBooks){await s.open('book='+b+'&niese='+(b===1?27:1));for(const l of ['greek','english'])await s.page.check('#'+l+'-pane-select');const menu=await s.page.locator('#niese-selector').evaluate(n=>[...n.options].filter(o=>o.value).map(o=>Number(o.value)));if(base&&JSON.stringify(menu)!==JSON.stringify(base.books.find(x=>x.book===b).menu))throw Error('Previous menu changed '+b);r.books.push({book:b,menu});
  for(const n of menu){await s.select(n);const a=await s.snapshot(),row={book:b,number:n,text:Object.fromEntries(Object.entries(a.languages).map(([l,t])=>[l,sha(norm(t))])),note:a.note,unavailable:a.unavailable,duplicates:a.duplicates,sourceIDs:a.sourceIDs,paneDOM_sha256:sha(JSON.stringify(a.paneDOM))};if(base&&JSON.stringify(row)!==JSON.stringify(base.selections.find(x=>x.book===b&&x.number===n)))throw Error('Prior selection changed '+b+'.'+n);r.selections.push(row);}console.log('Prior book',b,'selections',menu.length,'cumulative',r.selections.length);fs.writeFileSync(path.join(P,mode==='baseline'?'BASELINE_PROTECTED_BROWSER.json':'FINAL_PROTECTED_BROWSER.json'),JSON.stringify(r,null,2));}
 if(r.selections.length!==7350||r.views.length!==135)throw Error('Incomplete actual baseline population'); if(r.errors.length)throw Error('Unexpected browser errors '+JSON.stringify(r.errors));r.status='PASS';
}catch(e){r.status='FAIL';r.failure=String(e);throw e;}finally{r.finished=new Date().toISOString();fs.writeFileSync(path.join(P,mode==='baseline'?'BASELINE_PROTECTED_BROWSER.json':'FINAL_PROTECTED_BROWSER.json'),JSON.stringify(r,null,2)+'\n');await s.close();}console.log(JSON.stringify({status:r.status,selections:r.selections.length,views:r.views.length}));}
main().catch(e=>{console.error(e);process.exitCode=1;});
