"""Seal independently completed local book evidence; never substitutes for review or QA."""
from prepare_review import *
import subprocess, shutil
BASE='ad3158b7a86dea6997510b3de17f2e510c23367c'
sha=digest
b=int(sys.argv[1]); d=packet(b)
read=lambda p:json.loads(p.read_text(encoding='utf8'))
src=read(d/'FINAL_SOURCE_QA.json'); browser=read(d/'IMPLEMENTATION_BROWSER_QA.json'); ranges=read(d/'RANGE_BROWSER_QA.json')
protected=read(PACK/'PROTECTED_BROWSER_QA.json'); exceptions=read(PACK/'BOUNDED_BASELINE_EXCEPTIONS.json')
for record in [src,browser,ranges,protected,exceptions]: assert record['result']=='PASS'
assert not src['pending_editorial_decisions']
plan=read(d/'APPROVED_MARKER_PLAN.json'); rows=read(d/'BOUNDARIES.json')
if isinstance(rows,dict): rows=rows['boundaries']
head=subprocess.check_output(['git','rev-parse','HEAD'],cwd=ROOT,text=True).strip()
canonical=subprocess.check_output(['git','-C',r'C:\Users\Pollard_R\Git\LatinJosephus-v2-development','rev-parse','HEAD'],text=True).strip()
evidence={p.name:sha(p.read_bytes()) for p in [d/'FINAL_SOURCE_QA.json',d/'IMPLEMENTATION_BROWSER_QA.json',d/'RANGE_BROWSER_QA.json',PACK/'PROTECTED_BROWSER_QA.json',PACK/'BOUNDED_BASELINE_EXCEPTIONS.json']}
count=browser['projections']['identities']; intervals=browser['projections']['Latin_starts']
cert={'book':b,'status':'LOCAL_CERTIFIED_READY_FOR_COORDINATED_INTEGRATION','base_commit':BASE,'evidence_HEAD':head,'canonical_HEAD_read_at_seal':canonical,'canonical_advance':canonical!=BASE,'branch':'antiquities-niese-12-13','worktree':str(ROOT),'runtime':str(RUNTIME),'published_baseline_selectable':3157,'local_added_selectable':count,'local_added_nonempty_Latin_intervals':intervals,'Greek_marker_operations':len(plan['Greek_authorized_marker_operations']),'Latin_section_milestones':sum(x['kind']=='INSERT_LATIN_SECTION_MILESTONE' for x in plan['Latin_authorized_marker_operations']),'Latin_end_markers':sum(x['kind']!='INSERT_LATIN_SECTION_MILESTONE' for x in plan['Latin_authorized_marker_operations']),'retained_Latin_starts':intervals-sum(x['kind']=='INSERT_LATIN_SECTION_MILESTONE' for x in plan['Latin_authorized_marker_operations']),'no_independent_Latin_intervals':src['no_independent_Latin_intervals'],'whole_section_absence_claims':src['whole_section_Latin_absence_claims'],'pending_editorial_decisions':[],'source_recovery':'PASS: independent raw tag removal and stored exact inverse against pinned LF bytes; all narrative, IDs, sameAs and English preserved','reader_QA':'PASS: every selection, interval, language context, qualification and actual chapter/subchapter range; deep links, history, navigation, reload and themes','protected_QA':'PASS; exact inherited exceptions separately reproduced in frozen baseline and candidate','evidence_sha256':evidence,'integration_limit':'Local certification only; reconcile against then-current canonical code. No merge, push, preview change or deployment.'}
save(d/'CERTIFICATE.json',cert)
qa=read(d/'QA.json');qa.update({'status':cert['status'],'reader_certification':'PASS: see CERTIFICATE.json and its bound source/browser/range/protected evidence','completion_certificate':True,'pending_editorial_cases':[],'final_reader_enabled':True});save(d/'QA.json',qa)
human=d/'BOUNDARIES.md';human.write_text(human.read_text(encoding='utf8').replace('Provisional while review is incomplete. XML candidates are not source approval.','All individual reviews and decisions are closed; see CERTIFICATE.json for final local implementation and reader certification.'),encoding='utf8')
roman='XII' if b==12 else 'XIII'
(d/'REPORT.md').write_text(f'# Antiquities {roman}: locally certified\n\nStatus: LOCAL_CERTIFIED_READY_FOR_COORDINATED_INTEGRATION. Independently reviewed {count} Greek starts and {count} Latin candidates, with {intervals} nonempty Latin intervals. {cert["retained_Latin_starts"]} starts are retained, {cert["Latin_section_milestones"]} Latin section milestones added, {cert["Latin_end_markers"]} narrative end markers added, and {cert["Greek_marker_operations"]} independently verified Greek marker operations adopted. Explicit operations and byte coordinates are in APPROVED_MARKER_PLAN.json.\n\nNo pending editorial decisions. Sections without independent Latin intervals: {src["no_independent_Latin_intervals"]}; see the recorded correspondence and reader notices rather than infer whole-section absence. Source words, whitespace, spelling, punctuation, transmitted order, labels, paragraphs, apparatus, IDs and sameAs are preserved. Independent inverse recovery and node/raw-byte locator validation passed. English bytes and Whiston behavior are unchanged.\n\nEvery new identity was actually selected in our own local build. Exact intervals, Greek/English context, qualifications, final extent, full narrative partition and every actual chapter/subchapter range passed. Deep links, previous/next, reload/history, pane switching, unique IDs and light/dark themes passed. Protected Antiquities I–VIII/X, contents, traditional/Bamberg, Alignment, Whiston, Bellum including Lodge and other affected works passed comparison with our frozen baseline. The two precisely bounded inherited exceptions are documented in the batch packet.\n\nPublished baseline: 3,157 selectable identities. This book adds {count} local selections and {intervals} nonempty Latin intervals; these totals are distinct. Pinned base: {BASE}. Evidence HEAD before this certificate: {head}. Canonical HEAD observed at sealing: {canonical}. Branch: antiquities-niese-12-13. Worktree: {ROOT}. Runtime: {RUNTIME}. QA origins and actual profile isolation are recorded in browser evidence.\n\nCERTIFICATE.json binds the evidence hashes; FILE_MANIFEST.json lists exact packet bytes. SOURCE_AUTHORITY.md and BASELINE.json retain absolute sources and provenance. BOUNDARIES.json/BOUNDARIES.md retain the individual reviews. This certificate authorizes readiness for coordinated integration only; nothing has been merged, pushed or published.\n',encoding='utf8')
with (d/'SOURCE_AUTHORITY.md').open('a',encoding='utf8') as f:f.write(f'\nFinal local seal: all {count} printed Greek starts and Latin candidates independently reviewed. The approved marker plan, inline paratext exclusions, executable identity exceptions and final hashes are bound by CERTIFICATE.json. The complete narrative partition and exact recovery passed. Canonical HEAD re-observed read-only: {canonical}; frozen source inputs were not replaced. Final local implementation and reader QA passed; published sources are unchanged.\n')
save(d/'FILE_MANIFEST.json',{'book':b,'base_commit':BASE,'files':[{'path':str(p.relative_to(ROOT)).replace(chr(92),'/'),'sha256':sha(p.read_bytes()),'bytes':p.stat().st_size} for p in sorted(d.rglob('*')) if p.is_file() and p.name!='FILE_MANIFEST.json']})
print('Book',b,'certificate sealed at evidence HEAD',head)
