"""Record only page images actually examined in this review session."""
from prepare_review import *
from record_review import apply
shared=json.loads((PACK/'BASELINE.json').read_text(encoding='utf8'))
for src,dst in [('niese-title-005.png','Niese_III_title_PDF005.png'),('loeb-title-007.png','Loeb_VII_title_PDF007.png')]:shutil.copyfile(RUNTIME/src,PACK/dst)
title={'Niese':{'PDF_page':5,'image':'Niese_III_title_PDF005.png','observed':'FLAVII IOSEPHI OPERA; BENEDICTVS NIESE; VOL. III; ANTIQVITATVM IVDAICARVM LIBRI XI–XV; BEROLINI APVD WEIDMANNOS; MDCCCLXXXXII (1892)'},'Loeb':{'PDF_page':7,'image':'Loeb_VII_title_PDF007.png','observed':'JOSEPHUS; RALPH MARCUS; VII; JEWISH ANTIQUITIES BOOKS XII–XIV; WILLIAM HEINEMANN/HARVARD; MCMLXVI (1966)'}}
save(PACK/'TITLE_OBSERVATIONS.json',title)
for b,roman,span,pdfspan in [(12,'XII',[73,148],[145,220]),(13,'XIII',[151,233],[223,305])]:
 d=packet(b);baseline=json.loads((d/'BASELINE.json').read_text(encoding='utf8'))
 text=f'''# Antiquities {roman}: source authority and frozen inputs

Branch `antiquities-niese-12-13`, based exclusively on `{shared['base']}`. Actual canonical HEAD at creation/freeze was the same commit. Worktree: {ROOT}. Runtime: {RUNTIME}. Canonical files are read-only and no published state has been changed. No applicable AGENTS.md was found in the inventory or checked ancestors.

Canonical Latin transcription is the sole textual base. Niese III (Berlin: Weidmann, 1892) controls citation numbering. The title at PDF5 was visually examined; its contents statement is XI–XV. Selected original scan: {shared['PDF_inventory'][0]['path']}; SHA-256 {shared['PDF_inventory'][0]['sha256']}, 488 PDF pages. The differently named supplied reference copy is byte-identical. No PDF was modified.

Book {roman} narrative spans printed pp.{span[0]}–{span[1]}, PDF{pdfspan[0]}–{pdfspan[1]}. Opening and terminal images were inspected independently; Greek census records every explicit label. Opening identity 1 is implicit in XML and verified from the printed opening and running range; it is not deduced from arithmetic alone. Expected range: 1–{baseline['niese']['last']}.

Independent contextual control: Josephus VII, Jewish Antiquities XII–XIV, Ralph Marcus, Heinemann/Harvard, title-page 1966, visually inspected at PDF7. Actual file: {shared['PDF_inventory'][2]['path']}; SHA-256 {shared['PDF_inventory'][2]['sha256']}, 812 PDF pages. Loeb section windows must be checked individually; its chapter divisions do not certify Niese word starts.

BASELINE.json records actual absolute XML paths, snapshot paths, SHA-256, Git blob IDs and SHA-256, last source commits, encoding, line endings, IDs and sameAs. Locators use actual frozen worktree UTF-8 bytes. Git blobs and checkout LF/CRLF materializations are kept distinct. Input snapshots are unchanged. Contents in div2 n=0, num labels, notes and apparatus are excluded from narrative coordinates; mixed add/del/corr text and tails remain in the stream.

Accepted VIII/X method and certification records are pinned in the batch baseline. The reused mixed_mapper.py passed its 14 fixtures. Independent lxml text/tail validation and raw UTF-8/entity checks accompany each adopted candidate. Frozen structural references were hash-checked and are retained as print windows and traditional starts only.

Printed numeral position is an observation; the exact Greek word choice is recorded separately. SameAs and paragraph IDs identify comparison windows only. Unreviewed candidates remain explicitly unapproved. English/Whiston remains broader aligned context and is unchanged. No claim is made about the cause of missing or different Latin wording.
'''
 if b==13:text+='\nThe opening PDF223 has an erroneous XII running head, above the actual XIII opening and its immediately preceding XIII contents. The XIII narrative starts Τίνα μὲν οὖν; the terminal PDF305 prints XIII.432–433 and its book-13 subscription. The streams are not joined.\n'
 (d/'SOURCE_AUTHORITY.md').write_text(text,encoding='utf8',newline='\n')
obs={}
positions={145:{1:'Implicit first citation at I.1 opening; running range XII 1–7',2:'right margin at body line 3, alongside μεταπεσούσης',3:'right margin at line 7, alongside στασιαζόντων',4:'right margin at line 12, with prior ἐπικλήσει and κατέσχε on that line',5:'right margin at line 17, after prior αὐτῆς and alongside μαρτυρεῖ',6:'right margin at line 21, alongside quotation opening ἔστιν',7:'right margin at line 24, alongside authorial resumption Ἀγαθαρχίδης'},146:{8:'left margin line 3, after preceding γυπτον ἀγαγών, before ἐπεγνωκὼς',9:'left margin line 9, before preceding oath-clause ending and οὐκ ὀλίγοι on that line',10:'left margin line 11; στά- begins at line end and -σεις continues line 12',11:'left margin line 17 at II.1 Βασιλεύσαντος',12:'left margin line 22 with preceding δουλείας and Δημήτριος'},147:{13:'right margin line 2, at ἐρομένου after preceding συνηγωνίζετο',14:'right margin line 5, at μεμηνῦσθαι after preceding συναθροίσειν',15:'right margin line 9, at δοκεῖ after preceding γλῶτταν',16:'right margin line 14, at δόξας after preceding ἐκείνοις',17:'right margin line 17 at lower division 2, Ἀρισταῖος',18:'right margin line 20, with preceding captive description and καιρὸν',19:'right margin line 24, with preceding παρακαλῶν αὐτούς and προσλαβὼν'},148:{20:'left margin line 1, with preceding speech-introduction ending and quotation οὐ χρῆν',21:'left margin line 5, with preceding δουλευόντων and οὓς',22:'left margin line 9 at τὸν γὰρ',23:'left margin line 13, with preceding ἀπολελοιπόσιν and ἴσθι',24:'left margin line 18 at lower division 3, Ταῦτ᾽'},149:{25:'right margin line 1 after attribution Σωσιβίου and beginning ὡς ἄξιον',26:'right margin line 5, with preceding δραχμὰς ἑκατὸν εἴκοσι and καὶ περὶ',27:'right margin line 11 with prior ἐπεισήχθησαν and πλειόνων',28:'right margin line 14 with ἦν δὲ τοιοῦτον and quotation ὅσοι on same line',29:'right margin line 22 with preceding τὰ λύτρα and νομίζω',30:'right margin line 26 with preceding γεγονέναι and τὸ δίκαιον'}}
for p,items in positions.items():
 for n,position in items.items():obs[str(n)]={'edition':'Niese III, 1892','printed_page':p-72,'PDF_page':p,'image':f'evidence/Niese/page-{p}.png','observed_numeral_position':position,'word_boundary_status':'XML_WORD_START_CONFIRMED_FROM_PRINT','editorial_word_choice':'Retain the XML word start after comparing printed sentence/clause context; marginal alignment is not itself a word tag.'}
save(packet(12)/'PRINT_OBSERVATIONS.json',obs)
save(packet(13)/'PRINT_OBSERVATIONS.json',{'1':{'edition':'Niese III, 1892','printed_page':151,'PDF_page':223,'image':'evidence/niese-223.png','observed_numeral_position':'Implicit citation 1 at I.1 Τίνα μὲν οὖν opening; erroneous XII running head with 1–3 range; 2/3 marginal numbers in the following narrative','word_boundary_status':'XML_WORD_START_CONFIRMED_FROM_PRINT','editorial_word_choice':'Opening identity is the book-13 retrospective sentence.'},'433':{'edition':'Niese III, 1892','printed_page':233,'PDF_page':305,'image':'evidence/niese-305.png','observed_numeral_position':'right margin first body line at καὶ, after preceding procuration notice; ending and book-13 subscription below','word_boundary_status':'XML_WORD_START_CONFIRMED_FROM_PRINT','editorial_word_choice':'Keep the XML terminal retrospective clause; no following-book text.'}})
apply(12)
