const {fs,path,P,norm,sha,session}=require('./browser_common.cjs');
async function main(){const s=await session('final'),accepted=fs.existsSync(path.join(P,'FINAL_EXPECTED_INTERVALS.json')),expected=JSON.parse(fs.readFileSync(path.join(P,accepted?'FINAL_EXPECTED_INTERVALS.json':'SECURE_EXPECTED_INTERVALS.json'))),r={scope:accepted?'ACCEPTED_BOOKXX_BROWSER_QA':'ROUTINE_BOOKXX_BROWSER_QA_WITH_EDITORIAL_HOLDS',sourceBuild:JSON.parse(fs.readFileSync(path.join(P,'CANDIDATE_BUILD.json'))).source_commit,status:'RUNNING',started:new Date().toISOString(),editorialCertification:false,selections:[],interactions:[],errors:s.errors};
try{
 await s.open('book=20&niese=1');for(const l of ['greek','english'])await s.page.check('#'+l+'-pane-select');
 const census=await s.page.evaluate(()=>{const q=window.__qa,d=q.getData();return {menu:[...document.querySelector('#niese-selector').options].filter(o=>o.value).map(o=>Number(o.value)),Greek:q.antiquitiesNieseStartEntries('Greek',d.Greek).map(e=>e.number),Latin:q.antiquitiesNieseStartEntries('Latin',d.Latin).map(e=>e.number)};});
 const identities=Array.from({length:268},(_,i)=>i+1);if(JSON.stringify(census.menu)!==JSON.stringify(identities)||JSON.stringify(census.Greek)!==JSON.stringify(identities))throw Error('268 exact Greek/menu identities');r.census=census;
 for(const e of expected){await s.select(e.number);const a=await s.snapshot();if(norm(a.languages.Greek)!==norm(e.Greek)||norm(a.languages.English)!==norm(e.English)||!a.EnglishContext||a.duplicates.length){fs.writeFileSync(path.join(P,'XX_BROWSER_DIFFERENCE.json'),JSON.stringify({expected:e,actual:a},null,2));throw Error('Greek/Whiston interval or duplicate IDs '+e.number);}
  if(e.hold||e.unavailable){if(norm(a.languages.Latin)!==''||!a.unavailable?.includes(e.qualification))throw Error('Explicit editorial hold/unavailability '+e.number);}else if(norm(a.languages.Latin)!==norm(e.Latin)||a.note!==e.qualification){fs.writeFileSync(path.join(P,'XX_BROWSER_DIFFERENCE.json'),JSON.stringify({expected:e,actual:a},null,2));throw Error('Individually reviewed Latin interval '+e.number);}
  r.selections.push({number:e.number,Greek:'EXACT_FULL_INTERVAL_PASS',English:'PRESERVED_ALIGNED_CONTEXT_PASS',Latin:e.hold?'EXPLICIT_EDITORIAL_HOLD_PASS':e.unavailable?'APPROVED_UNAVAILABLE_PASS':'EXACT_FULL_INTERVAL_PASS',Greek_sha256:sha(norm(a.languages.Greek)),Latin_sha256:sha(norm(a.languages.Latin)),English_sha256:sha(norm(a.languages.English)),duplicateIDs:0});if(e.number%50===0)console.log('XX individual browser selections',e.number);
 }
 for(const n of [1,5,6,10,51,54,100,103,105,129,136,169,173,182,189,197,200,215,224,252,259,266,267,268]){
  await s.open('book=20&niese='+n);await s.page.reload();await s.page.waitForFunction(()=>window.__qaReady);if(n<268){await s.page.click('#niese-next');await s.page.waitForFunction(n=>window.__qaRenderedState?.nieseNum===String(n),n+1);await s.page.click('#niese-previous');await s.page.waitForFunction(n=>window.__qaRenderedState?.nieseNum===String(n),n);await s.page.goBack();await s.page.waitForFunction(n=>window.__qaRenderedState?.nieseNum===String(n),n+1);await s.page.goForward();await s.page.waitForFunction(n=>window.__qaRenderedState?.nieseNum===String(n),n);}else if(!await s.page.locator('#niese-next').isDisabled())throw Error('Terminal next allows269');if(n===1&&!await s.page.locator('#niese-previous').isDisabled())throw Error('Opening previous');r.interactions.push({number:n,directURLReloadNextPreviousHistory:'PASS'});
 }
 await s.open('book=20&niese=268');const last=await s.snapshot();if(!norm(last.languages.Latin).endsWith(norm(expected[267].Latin))||!norm(last.languages.Greek).endsWith(norm(expected[267].Greek)))throw Error('Complete final tail');r.bookEnd={number:268,LatinEnd:norm(last.languages.Latin).slice(-180),GreekEnd:norm(last.languages.Greek).slice(-180),VitaIncluded:false};
 await s.open('book=20&niese=1');const first=await s.snapshot();if(norm(first.languages.Greek).startsWith('περιέχει'))throw Error('Duration notice counted as1');r.bookOpening={durationOutside1:true,Greek:norm(first.languages.Greek).slice(0,150),Latin:norm(first.languages.Latin).slice(0,150)};
 for(const l of ['greek','english']){await s.page.uncheck('#'+l+'-pane-select');if(await s.page.locator('#'+l).isVisible())throw Error('Hide pane '+l);await s.page.check('#'+l+'-pane-select');if(!await s.page.locator('#'+l).isVisible())throw Error('Show pane '+l);}
 for(const theme of ['light','dark']){await s.page.evaluate(t=>setTheme(t),theme);await s.page.waitForTimeout(400);await s.page.screenshot({path:path.join(P,'evidence','XX-reader-'+theme+'.png'),fullPage:true});}r.panesAndThemes='PASS';
 await s.open('book=19');await s.page.selectOption('#book-selector','20');await s.page.waitForFunction(()=>window.__qaRenderedState?.bookNum==='20');if((await s.snapshot()).state.bookNum!=='20')throw Error('XIX→XX transition');r.XIXtoXX='PASS';
 if(r.errors.length)throw Error('Browser console/network errors '+JSON.stringify(r.errors));r.status='PASS';
}catch(e){r.status='FAIL';r.failure=String(e);throw e;}finally{r.finished=new Date().toISOString();fs.writeFileSync(path.join(P,'BOOKXX_BROWSER.json'),JSON.stringify(r,null,2)+'\n');await s.close();}console.log(JSON.stringify({status:r.status,identities:r.selections.length,exactLatin:r.selections.filter(s=>s.Latin==='EXACT_FULL_INTERVAL_PASS').length,editorialHolds:r.selections.filter(s=>s.Latin==='EXPLICIT_EDITORIAL_HOLD_PASS').length,interactionCases:r.interactions.length}));}
main().catch(e=>{console.error(e);process.exitCode=1;});
