from record_review import *
record('130-157',[
 (130,'Et ex inde ueniens',312,'Lydda hearing and four rebels.'),
 (131,'Et illos quidem quadratus',312,'Execution and sending high priest and commander to Rome.'),
 (132,'iussitque primatibus',312,'Other disputants ordered before emperor.'),
 (133,'Ipse uero metuens',312,'Peaceful Jerusalem visit and return to Antioch.'),
 (134,'Cumanus autem et qui',313,'Hearing date for deputation.'),
 (135,'Habebant enim trocinium',313,'Court patronage countered by Agrippa and Agrippina.'),
 (136,'XII Claudius autem',313,'Judgment and punishments; literal XII retained.'),
 (137,'XIII Misit autem',313,'Felix appointment, distinct Bamberg XIII.'),
 (138,'Cumque decimum principatus',313,'Agrippa territory grant; Latin decimum versus Greek δωδέκατον retained.'),
 (139,'Aggripas uero sumens',313,'Drusilla marriage and Epiphanes refusal; tail p300.'),
 (140,'Mariam uero dedit',314,'Mariamne marriage and daughter.'),
 (141,'Nuptiae siquidem inter',314,'Drusilla divorce introduction.'),
 (142,'Dum felix in iudaeam',314,'Felix desire and intermediary invitation; personal-name variant preserved.'),
 (143,'Illa uero non benefaciens',314,'Berenice envy and departure from custom.'),
 (144,'Ex quo susceptum',314,'Son Agrippa and Vesuvius forward reference.'),
 (145,'Berenices uero post',314,'Widow, incest allegation and Polemon marriage.'),
 (146,'Polemon autem flexus',315,'Wealth, separation and abandonment of observance.'),
 (147,'Eodem uero tempore',315,'Mariamne and Demetrius, child and narrative promise.'),
 (148,'XIIII Claudius interae',315,'Death and Agrippina family; literal XIIII preserved.'),
 (149,'quo moriente uiduatam',315,'Claudius marriage, Domitius and Messalina children.'),
 (150,'Erat autem ei et antonia',315,'Antonia and Octavia engagement to adopted Nero.'),
 (151,'Agrippina autem metuens',316,'Britannicus fear and plan for Claudius death; parenthetic consummation begins152.'),
 (152,'sicut erat sermo tractauit',316,'Reported killing and Burrus escorts Nero; boundary occurs within sentence.'),
 (153,'Nero si quidem',316,'Nero murders and retribution.'),
 (154,'Sed de his quidem',316,'Historians distorted Nero through gratitude or hatred.'),
 (155,'Mirandi tamen amęnon',316,'Earlier history likewise corrupted without personal hatred.'),
 (156,'Sed his quidem qui',316,'Dismissal of writers indifferent to truth.'),
 (157,'Nos enim preapositum',316,'Josephus truth, calamities and return to Jewish narrative.')])
