from record_review import *
record('158-205',[
 (158,'primo namque imperio',317,'Azizus death and Armenian appointment.'),
 (159,'Sed agrippe donauit',317,'Galilee and Peraean gifts; local place/count compression retained.'),
 (160,'XIIII. Res itaque',317,'Deteriorating Judaea; inherited literal XIIII distinct from prior numeral.'),
 (161,'Quorum multos cottidie',317,'Felix executions and capture of Eleazar.'),
 (162,'Habens autem inimicitias',317,'Jonathan admonition and Felix resentment.'),
 (163,'Pro hac igitur causa',317,'Bribery and murder plan; complete p304 continuation.'),
 (164,'Ascenderunt quidam eorum',318,'Disguised worshippers kill Jonathan.'),
 (165,'Cumque mors enim',318,'Unpunished killing encourages murders in city and temple.'),
 (166,'Ob quam causam arbitror',318,'Narrator explains destruction and punishment.'),
 (167,'Opera si Rogo te',318,'Brigand impiety and desert invitation; irregular incipit preserved.'),
 (168,'Dicentes sedi praeuidentia',318,'Promise of signs, deception and Felix punishment.'),
 (169,'XV Hoc eni in tempore',318,'Egyptian prophet and Mount of Olives; Bamberg XV source text retained.'),
 (170,'uelle dicens eis',319,'Claim that walls will fall and entrance open.'),
 (171,'felix autem dum',319,'Armed attack, deaths and captures.'),
 (172,'Ipse aut aegyptius',319,'Escape and renewed brigand incitement.'),
 (173,'XVI Inter haec',319,'Caesarea citizenship dispute; literal XVI retained.'),
 (174,'Haec audientes praefecti',319,'Leaders flogged and temporary peace.'),
 (175,'Rursus enim iudaei',319,'Jewish wealth and renewed insults.'),
 (176,'Illi uero pecuniis',319,'Syrian military connections, stones and Jewish victory; p306 continuation.'),
 (177,'Felix autem cum uidissent',320,'Governor troops and plunder.'),
 (178,'Iudaeorum uero modestiores',320,'Moderate appeal, recall and concession.'),
 (179,'Hoc itaque tempore rex agrippas dedit',320,'Agrippa appoints Ishmael; disambiguated from the similar211 incipit by actual appointment wording.'),
 (180,'Exorta est et pontificum',320,'Priestly gangs and unchecked violence; tail p307.'),
 (181,'Tantam siquidem inpudentiam',321,'Tithe seizures, starvation and violence over justice.'),
 (182,'XVII Portio siquidem',321,'Festus appointment, accusation of Felix and Pallas intercession.'),
 (183,'Interea primates syrorum',321,'Syrian bribery to revoke citizenship; source office wording retained.'),
 (184,'Berillus ergo imperatorum',321,'Letter and future cause of war.'),
 (185,'Festo igitur in iudaeam',321,'Festus arrives amid brigand devastation.'),
 (186,'Precipue namque siccarii',321,'Sicarii weapons and etymology; tail p308.'),
 (187,'Hi namque latenter',322,'Festival assassination and village burning.'),
 (188,'Interea diuersis rebus',322,'Festus destroys desert deception; no correction to added introductory wording.'),
 (189,'XVIII Hoc tempore rex',322,'Agrippa palace addition; literal XVIII retained.'),
 (190,'Quod palatium factum',322,'Palace history and view into temple.'),
 (191,'Haec itaque uidentes',322,'Temple privacy and new wall.'),
 (192,'hic uero paries',322,'Obscured dining room and Roman portico; p309 continuation.'),
 (193,'In his igitur indignatus',323,'Order to demolish and request for embassy.'),
 (194,'Tunc permittente festo',323,'Embassy and officials; inherited ducem wording preserved.'),
 (195,'Nero autem audiens',323,'Permission, Poppaea and retained hostages.'),
 (196,'Rex igitur haec',323,'Joseph Cabi appointment.'),
 (197,'Porro caesar albinum',323,'Albinus appointment and Ananus succession; traditional IX begins here.'),
 (198,'Hunc et enim seniorem',323,'Elder Ananus success and sons; literal repetition protected.'),
 (199,'Ananus autem iunior',323,'Younger Ananus character and Sadducean severity; normal correspondence review.'),
 (200,'XVIIII Cum ergo',324,'Council and stoning accusation; preserve every spelling and literal XVIIII, no authenticity judgment.'),
 (201,'Qui autem uidebantur',324,'Moderate opposition and appeal to king.'),
 (202,'Quidam uero eorum',324,'Delegation meets Albinus and jurisdiction objection.'),
 (203,'Albinus autem eorum',324,'Threat, deposition and Jesus Damneus appointment.'),
 (204,'Cumque albinos',324,'Albinus secures peace and kills sicarii.'),
 (205,'Pontifex igutur ananias',324,'Ananias wealth, honor and gifts.')])
