from record_review import *
record('023-060',[
 (23,'Aben nerigus autem',294,'Reception, marriage to daughter and tributary territory.'),
 (24,'Monobazus autem cum',294,'Father recalls son and grants Carrhae; next terrain clause belongs25.'),
 (25,'terra fertilis ammoni',294,'Carrhae terrain and Noah ark relics; appositional clause within Latin sentence.'),
 (26,'Commorabatur itaque iazatis',294,'Only opening residence clause survives; rest of26 absent at normal position. Requires completed displacement review.'),
 (27,None,294,'Helena summons grandees and states succession preference: no normal-slot counterpart.'),
 (28,None,295,'Grandees bow and confirm Izates: no normal-slot counterpart.'),
 (29,None,295,'Proposal to kill brothers and kin: no normal-slot counterpart.'),
 (30,None,295,'Helena thanks and postpones killing: no normal-slot counterpart.'),
 (31,None,295,'Detention and interim regent advice: no normal-slot counterpart.'),
 (32,None,295,'Monobazus interim diadem, ring and sampsera: no normal-slot counterpart.'),
 (33,None,295,'Izates arrives and succeeds yielding brother: no normal-slot counterpart.'),
 (34,None,296,'Ananias instruction to royal women: inherited Latin num34 contains terminal37 fragment, not34.'),
 (35,None,296,'Instruction of Izates and Helena and return with Ananias: no normal-slot counterpart.'),
 (36,None,296,'Izates finds imprisoned relatives: no normal-slot counterpart.'),
 (37,'Darta banem particum',296,'Only final dispatch to Parthian Artabanus survives. Do not assign it to34 from paragraph ID.'),
 (38,'Cumque legibus crederet',296,'Conversion resolve and circumcision requirement; inherited chapter placement preserved.'),
 (39,'Quod dum cognouisse',296,'Mother warns of subject hostility.'),
 (40,'et illa quidem haec',296,'Mother persists; Ananias threatened departure remains in40.'),
 (41,'Cui mater ait metuere',297,'Fear of blame and permission to worship without circumcision; inherited speaker wording retained.'),
 (42,'ueniasque illi daturum',297,'Divine allowance for necessity and king persuaded; conjunctive Latin clause retained.'),
 (43,'Post haec autem cum',297,'Later Galilean Eleazar urges circumcision.'),
 (44,'Qui cum intrasset',297,'Entry, reading Moses and admonition to act.'),
 (45,'Quam diu sine',297,'Question and injunction to read circumcision law.'),
 (46,'Haec audiens rex actum',297,'Circumcision performed and report to mother and teacher.'),
 (47,'Qui repente non',297,'Both fear deposition and danger to themselves.'),
 (48,'Deus autem praesens',298,'Divine protection, future rescues and forward narrative promise.'),
 (49,'Igitur helena regis',298,'Helena wishes to visit Jerusalem; petition belongs49.'),
 (50,'quo matri petenti',298,'Son agrees, equips journey and accompanies mother.'),
 (51,'Cuius aduentus ierosolimitis',298,'Arrival beneficial; Bamberg VI begins later at famine, inside51, not at its start.'),
 (52,'Cumque uenissent haec',298,'Returning supplies distributed and enduring memory; tail on p285 checked.'),
 (53,'Cuius filius iazatis',299,'Izates sends money and narrator postpones other royal benefactions.'),
 (54,'Artabanus itaque rex',299,'Artabanus chooses refuge with Izates after conspiracy.'),
 (55,'Sumptis ergo cognatorum',299,'Thousand attendants; road encounter wording is delayed into following Latin sentence.'),
 (56,'Cumque ipse illum',299,'Recognition asymmetry, approach, prostration and plea; retains locally reordered road encounter.'),
 (57,'Perspice siquidem inconstantiam',299,'Instability of fortune and shared danger to kings.'),
 (58,'Haec ergo artabanus',300,'Tears and Izates dismounting; reassurance boundary59 under separate editorial consideration.'),
 (59,'habe inquit fiducia',300,'Candidate keeps complete Latin reassurance phrase together although Greek58 ends with θάρσησον.'),
 (60,'Regem haec dicens',300,'Mounting and walking honor, protest and conditional oath.')])
rows=json.loads((PACK/'IDENTITIES.json').read_text(encoding='utf-8'))
for n in [26,37]:rows[n-1]['candidate']['assessment']='PARTIAL_CORRESPONDENCE';rows[n-1]['candidate']['correspondence']='PARTIAL';rows[n-1]['Latin_review_status']='EDITORIAL_DECISION_REQUIRED'
for n in [58,59]:rows[n-1]['Latin_review_status']='EDITORIAL_DECISION_REQUIRED'
save(PACK/'IDENTITIES.json',rows)
