from record_review import *
record('061-104',[
 (61,'Tunc ille in equo',300,'Royal hospitality and consolation on common fortune.'),
 (62,'scripsit parthis suadens',300,'Request to restore Artabanus with promises and oaths.'),
 (63,'Parthis uero suscipere',300,'Parthians cannot accept because Cinnamus reigns; fear of conflict.'),
 (64,'Agnoscens eorum cinnamus',301,'Cinnamus invites Artabanus; upbringing and character compressed away.'),
 (65,'Cui utique credens',301,'Artabanus returns and Cinnamus transfers diadem.'),
 (66,'Sic igitur artabanis',301,'Restoration and reciprocal benefactions.'),
 (67,'Nam et tyara',301,'Upright tiara and golden bed privileges.'),
 (68,'Deditque ei maximam',301,'Nisibis gift, city history and closure of honors.'),
 (69,'Post paululum uero tempus artabanus',301,'Vardanes succession and military invitation.'),
 (70,'cui tamen suadere',301,'Izates refuses because Rome too strong.'),
 (71,'In super dumisisset',302,'Five sons education, mother pilgrimage and warnings to Vardanes.'),
 (72,'In his ergo parthorum',302,'Threat to Izates frustrated by God.'),
 (73,'agnoscentes enim parthi',302,'Parthians kill Vardanes and transfer rule.'),
 (74,'Cui etiam post paululum',302,'Gotarzes death, Vologeses and brothers dominions.'),
 (75,'Monobazus igitur regis',302,'Kin wish to adopt Jewish customs.'),
 (76,'Horum nisus subiectus',302,'Grandees conceal anger and seek chance for revenge; tail p289 checked.'),
 (77,'Quam ob rem ad abiam',303,'Invitation, payment, betrayal promise and oath.'),
 (78,'his itaque flexus',303,'Arab advance and army flight before first battle.'),
 (79,'Non tamen iazates',303,'Izates discovers treason, kills culprits and attacks next day.'),
 (80,'Omnes autem simul',303,'Rout, siege and booty; Latin places Abias suicide before return.'),
 (81,'Primo quidem con amine',303,'Second conspiracy seeks Parthian ruler; complete tail p290.'),
 (82,'haec audiens rex parthorum',304,'Demand to return honors and threat of war.'),
 (83,'Hic auditis iazatis',304,'Distress and shame of surrendering gifts from fear.'),
 (84,'Sciens in super',304,'Knows concession will not stop enmity; entrusts danger to God.'),
 (85,'eumque maximum habere',304,'God as ally, family secured and resources gathered; Greek burning variant not harmonized.'),
 (86,'Venientem uero parthorum',304,'Army and camps near boundary river.'),
 (87,'Quo facto uenit',304,'Envoy describes extent and subject kings; tail p291 preserved.'),
 (88,'Interininatus pariter',305,'Threat against ungrateful Izates and his God.'),
 (89,'Haec dicente nuntio',305,'Reply, supplication, ashes and family fasting.'),
 (90,'Dominator domine sin',305,'Full direct prayer, source spelling retained.'),
 (91,'Et ille quidem hoc',305,'Prayer heard, invasion report and withdrawal.'),
 (92,'Post paululum uero tempus cum',305,'Age, reign, children and death.'),
 (93,'Successionem regni fratrem',306,'Monobazus rewarded for preserving kingdom.'),
 (94,'Cuius mater helena',306,'Helena grief, return and death.'),
 (95,'Monobazus autem et illius',306,'Bones sent to Jerusalem tombs.'),
 (96,'Sed quae cumque rex',306,'Forward promise concerning Monobazus.'),
 (97,'Igitur dum iudaeam',306,'Theudas promises Jordan crossing.'),
 (98,'Haec ergo dicens',306,'Followers deceived, cavalry attack and beheading; Latin lacks transport of head to Jerusalem.'),
 (99,'Haec sunt ergo',306,'Closure of Fadus narrative.'),
 (100,'VII Venitque fado',307,'Tiberius Alexander and paternal religious comparison; literal VII protected.'),
 (101,'Horum ergo temporibus',307,'Famine and Helena supplies.'),
 (102,'Super autem iacobum',307,'Crucifixion of sons of Judas; reordered personal names retained.'),
 (103,'VIII Herodes autem',307,'Priestly appointment and Cumanus succession; literal VIII protected.'),
 (104,'Defunctusque est herodes',307,'Herod death, children and grant to young Agrippa.')])
