from record_review import *
record('231-268',[
 (231,'post illos itaque XIII',328,'Eighteen priests, Nebuchadnezzar and captivity; tail p315.'),
 (232,'Tempus enim pontificatus',329,'Duration and monarchy; differing day count remains unchanged.'),
 (233,'Post tempus autem',329,'Cyrus releases captives and permits rebuilding.'),
 (234,'His itaque remeantibus',329,'Joshua succession and fifteen priests; compressed count retained.'),
 (235,'XIIII. Primusque antiochus',329,'Menelaus removed and Joakim appointed; inherited plain XIIII unchanged.'),
 (236,'Propterea et ananias',329,'Onias/Ananias in Egypt and temple appointment.'),
 (237,'Sed de templo quidem',329,'Prior temple account, Joakim death and vacancy; neme retained as transcription.'),
 (238,None,330,'Hasmonean leadership, war and Jonathan seven-year priesthood have no normal-slot counterpart. Need full-book review confirmation.'),
 (239,'quo per insidias moriente',330,'Tryphon murder and Simon succession; relative antecedent unavailable in local wording.'),
 (240,'huic per dolum quoque',330,'Simon murder and Hyrcanus; following kingship clause needs241 adjudication.'),
 (241,'Is namque primus',330,'Candidate starts at diadem statement, with reordered Alexander succession; earlier kingship clause may also correspond.'),
 (242,'Alexander autem cum',330,'Alexander death, Alexandra and Hyrcanus tenure.'),
 (243,'Post mortem namque',330,'Aristobulus overthrows Hyrcanus.'),
 (244,'Huius anno tertio',330,'Pompey conquest and restoration without diadem; p317 continuation.'),
 (245,'Habuit autem hyrcanus',331,'Hyrcanus duration and Parthian intervention; 23/24 variant protected.'),
 (246,'quidum tribus annis',331,'Antigonus siege and execution.'),
 (247,'Herodes uero commisso',331,'Herod appointment policy and Aristobulus exception.'),
 (248,'Aristobolum namque filium',331,'Appointment, marriage, popularity and drowning; filium variant protected.'),
 (249,'Post hunc autem',331,'Policy repeated by Archelaus and Romans.'),
 (250,'Sunt ergo uiri',331,'Priests through Titus and duration; 29/28 variant protected.'),
 (251,'Quorum quidam conuersati',332,'Government, high-priestly authority and conclusion.'),
 (252,'Cessius itaque florus',332,'Florus appointment, origin and wife; traditional XI starts here.'),
 (253,'Sic autem florus',332,'Worse than Albinus.'),
 (254,'Ille namque malignitatem',332,'Concealed versus ostentatious wrongdoing.'),
 (255,'Erat enim inflexibilis',332,'Cruelty, greed and shared brigand gains.'),
 (256,'quod opus non erat',332,'Intolerable plunder and flight abroad; p319 continuation.'),
 (257,'Florus igitur fuit',333,'Compulsion to war and regnal dates; opening rhetorical question compressed away.'),
 (258,'Sed ea quidem quaecumque',333,'Reference to completed Jewish War books.'),
 (259,'Hic igitur ponam',333,'Antiquities closure and historical extent; Latin decimum retained, distinct traditional XII.'),
 (260,'et quaecumque perpessi',333,'Assyrian/Babylonian, Persian/Macedonian and Roman experiences.'),
 (261,'Nisus sum autem',333,'Priests, royal succession and opening promise fulfilled.'),
 (262,'Dico siquidem cum',333,'Claim of unique Greek historical account.'),
 (263,'Habens enim indubitanter',333,'Education and pronunciation; damaged source spelling retained, p320 continuation.'),
 (264,'quippe cum apud nos',334,'Language skill and scriptural learning distinction.'),
 (265,'propterea multis in hoc',334,'Few achieve fruits of study.'),
 (266,'Non erit forsan',334,'Promise of autobiographical account; living witnesses clause absent here, no Vita import.'),
 (267,'In his ergo dicere',334,'Twenty books, sixty thousand lines, future recap and author date.'),
 (268,'proposui uero uobis',334,'Projected four-book theological/legal work; exact ending retained, Vita begins separately at printed321/PDF335.')])
rows=json.loads((PACK/'IDENTITIES.json').read_text(encoding='utf-8'))
for n in [240,241]:rows[n-1]['Latin_review_status']='EDITORIAL_DECISION_REQUIRED'
for n in [218,266]:rows[n-1]['candidate']['assessment']='PARTIAL_CORRESPONDENCE';rows[n-1]['candidate']['correspondence']='PARTIAL'
save(PACK/'IDENTITIES.json',rows)
