from record_review import *
record('105-129',[
 (105,'VIIII Seditione igitur',308,'Riot introduction and promised cause; literal VIIII retained.'),
 (106,'Instante festiuitate paschae',308,'Passover gathering and armed cohort precaution.'),
 (107,'hoc enim et priores',308,'Previous governors used same precaution.'),
 (108,'Cumque quarta dies',308,'Indecency, crowd anger and allegations against governor.'),
 (109,'Cumanus autem audiens',308,'Anger and exhortation to quiet.'),
 (110,'quibus dum suadere',308,'Failure to persuade and order to Antonia.'),
 (111,'Multitudo siquidem uidens',308,'Flight and crush through narrow exits; tail p295 checked.'),
 (112,'Viginti milia enim',309,'Death count, mourning and closing cause; repeated milia preserved.'),
 (113,'Non dum igitur luctus',309,'New calamity and Stephanus robbery.'),
 (114,'Audiens hoc cumanus',309,'Soldiers sent to plunder and arrest.'),
 (115,'Igitur uastatione facta',309,'Soldier tears Mosaic laws and blasphemes.'),
 (116,'Iudaei uero haec',309,'Crowd appeal at Caesarea; Cumanus fear introductory words belong116 in Greek.'),
 (117,'ne denuo tumultum',310,'Subordinate fear clause continues116; execution prevents second riot.'),
 (118,'X Post haec igitur',310,'Samaritan-Galilean hostility and route massacre; literal X retained.'),
 (119,'Primi siquidem galileorum',310,'Appeal and bribed neglect.'),
 (120,'Tum galilei dolentes',310,'Armed resistance and intolerable slavery.'),
 (121,'Primatibus autem eorum',310,'Leaders ignored; Eleazar and village destruction.'),
 (122,'Cumanis hoc audiens',310,'Sebastene cohort, army and captures; p297 continuation checked.'),
 (123,'primi uero ierosolimorum',311,'Sackcloth appeal and predicted devastation.'),
 (124,'Haec ergo dicentes',311,'Persuasion, dispersal and growing brigandage.'),
 (125,'Samaritanorum uero primates',311,'Samaritan accusation before Quadratus.'),
 (126,'et pro his quidem',311,'Roman authority argument and requested revenge.'),
 (127,'His ergo samaritae',311,'Jewish counteraccusation and Cumanus corruption.'),
 (128,'Quadratus autem cum',312,'Judgment postponed until visit.'),
 (129,'et illi quidem nihil',312,'Dismissal precedes Quadratus visit; Bamberg XI occurs after initial clause inside129.')])
