const fs=require('fs'),path=require('path'),http=require('http'),crypto=require('crypto');
const {chromium}=require('C:/Users/Pollard_R/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const packet=__dirname,site=JSON.parse(fs.readFileSync(path.join(packet,'ENVIRONMENT.json'))).build;
const expected=JSON.parse(fs.readFileSync(path.join(packet,'EXPECTED_INTERVALS.json')));
const report={result:'RUNNING',scope:'FRESH_COMBINED_BUILT_SITE',checks:[],availability:[],screenshots:[],errors:[],consoleErrors:[],requests:[]};
const save=()=>fs.writeFileSync(path.join(packet,'INTERACTION_QA.json'),JSON.stringify(report,null,2));
const norm=s=>String(s||'').replace(/\s+/g,' ').trim();
function narrative(n){const c=n.cloneNode(true);c.querySelectorAll('tei-num,tei-milestone,tei-note,tei-app,tei-rdg,.niese-context-note,.niese-correspondence-note,.structural-unavailable').forEach(x=>x.remove());return [...(c.matches?.('tei-p')?[c]:[]),...c.querySelectorAll('tei-p')].filter(x=>!x.closest('tei-div2[n="0"]')).map(x=>x.textContent).join('').replace(/\s+/g,' ').trim();}
function instrument(s){return s.replace('  bookTitle.innerText = activeWork.title;','  window.__combined={state:()=>({...state})};\n  bookTitle.innerText = activeWork.title;').replaceAll('setState(() => {','window.__combinedPending = setState(() => {').replace('    syncNavigationControls();','    syncNavigationControls(); window.__combinedRendered={...state}; window.__combinedRevision=(window.__combinedRevision||0)+1;').replace('  reload().then(() => {','  reload().then(() => { window.__combinedReady=true; document.querySelector("#collapse-settings")?.classList.add("show");');}
const server=http.createServer((req,res)=>{const u=new URL(req.url,'http://local');let f=path.resolve(site,'.'+decodeURIComponent(u.pathname));if(!f.startsWith(path.resolve(site)+path.sep)){res.statusCode=403;return res.end();}if(fs.existsSync(f)&&fs.statSync(f).isDirectory())f=path.join(f,'index.html');if(!fs.existsSync(f)){res.statusCode=404;return res.end();}let raw=fs.readFileSync(f);if(f.endsWith('renderTei.js'))raw=Buffer.from(instrument(raw.toString()));res.setHeader('Content-Type',({'.xml':'application/xml','.js':'text/javascript','.css':'text/css','.html':'text/html','.json':'application/json','.otf':'font/otf','.woff2':'font/woff2','.svg':'image/svg+xml'})[path.extname(f)]||'application/octet-stream');res.end(raw);});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin=`http://127.0.0.1:${server.address().port}`,browser=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'}),context=await browser.newContext({viewport:{width:1690,height:1100}}),page=await context.newPage();
page.on('pageerror',e=>report.errors.push(String(e)));page.on('console',m=>{if(m.type()==='error')report.consoleErrors.push(m.text());});page.on('requestfailed',r=>report.requests.push({url:r.url(),error:r.failure()?.errorText}));
async function open(route){await page.goto(origin+route);await page.waitForFunction(()=>window.__combinedReady);await page.evaluate(()=>document.fonts.ready);}
async function change(sel,value){await page.selectOption(sel,value);await page.evaluate(()=>window.__combinedPending);}
async function radio(sel){await page.check(sel);await page.evaluate(()=>window.__combinedPending);}
async function history(direction,view,n=null){const revision=await page.evaluate(()=>window.__combinedRevision);await page[direction]();await page.waitForFunction(({revision,view,n})=>window.__combinedRevision>revision&&window.__combinedRendered?.viewingLevel===view&&(n===null||Number(window.__combinedRendered.nieseNum)===n),{revision,view,n});}
async function snap(name){await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:path.join(packet,'screenshots',name+'.png')});report.screenshots.push('screenshots/'+name+'.png');}
async function contents(book){return await page.evaluate(({book})=>{const q=window.__combined.state(),u=new URL(location.href),g=document.querySelector('#greek .source-contents'),e=document.querySelector('#english .source-contents'),l=document.querySelector('#latin .source-contents');if(q.viewingLevel!=='contents-level'||u.searchParams.get('view')!=='contents'||Number(q.bookNum)!==book)throw Error('Contents state');if(['chapter','subchapter','bamberg','niese','unit'].some(k=>u.searchParams.has(k)))throw Error('Stale conflicting parameter');if(['chapterNum','subchapterNum','bambergId','sectionNum','nieseNum'].some(k=>q[k]!==null))throw Error('Stale state');if(document.querySelector('#chapter-selector').value!=='contents')throw Error('Chapter selector');const greek=[...g.children].filter(x=>x.localName.startsWith('tei-')).map(x=>x.textContent),english=[...e.querySelectorAll('tei-item tei-reg')].map(x=>x.textContent);if(english.length!==({8:15,9:14,10:11})[book])throw Error('Whiston count');if(!g.querySelector('tei-div'))throw Error('Greek list missing');if(l.textContent!=='No source table of contents is available for this witness.')throw Error('Latin false contents claim');if(g.querySelector('a')||e.querySelector('a'))throw Error('Speculative TOC links');if(e.querySelectorAll('tei-note[subtype="provenance"]').length!==1)throw Error('Duplicate note');return {Greek:greek,English:english,Latin:l.textContent,greekEntryElements:g.querySelectorAll('tei-item,tei-p').length};},{book});}
async function niese(book,n){const d=await page.evaluate(code=>{const text=eval('('+code+')');return {q:window.__combined.state(),text:Object.fromEntries(['Greek','Latin','English'].map(l=>[l,text(document.querySelector('#'+l.toLowerCase()))])),englishBroader:!!document.querySelector('#english .niese-context-note'),latinMissing:!!document.querySelector('#latin .structural-unavailable'),ids:[...document.querySelectorAll('[id]')].map(x=>x.id)};},narrative.toString());if(d.q.viewingLevel!=='niese-level'||Number(d.q.nieseNum)!==n||Number(d.q.bookNum)!==book)throw Error('Wrong Niese identity');for(const l of ['Greek','Latin'])if(d.text[l]!==norm(expected[book][l][n]))throw Error(`${book}.${n} ${l} interval changed: ${JSON.stringify({state:d.q,actual:d.text[l],expected:expected[book][l][n]})}`);if(!d.englishBroader||!d.text.English)throw Error('English must be labelled broader context');if(d.latinMissing!==(book===10&&n===108))throw Error('Absence state');if(new Set(d.ids).size!==d.ids.length)throw Error('Duplicate IDs');const u=new URL(page.url());if(u.searchParams.has('view')||['chapter','subchapter','bamberg','unit'].some(k=>u.searchParams.has(k))||Number(u.searchParams.get('niese'))!==n)throw Error('Stale Niese URL');return d.text;}
for(const width of [1690,1200])for(const theme of ['light','dark'])for(const book of [8,10]){
 await page.setViewportSize({width,height:1100});await open(`/antiquities/?book=${book}&view=contents&extra=keep#retained`);await page.evaluate(t=>setTheme(t),theme);await page.waitForTimeout(600);const c=await contents(book);if(width===1690)await snap(`Antiquities-${book}-contents-${theme}`);
 await radio('#niese-level');const section=book===8?187:108;await change('#niese-selector',String(section));await niese(book,section);if(width===1690)await snap(`Antiquities-${book}-niese-${section}-${theme}`);
 for(const lang of ['greek','english']){await page.uncheck('#'+lang+'-pane-select');await page.check('#'+lang+'-pane-select');await niese(book,section);}
 await change('#chapter-selector','contents');if(JSON.stringify(c)!==JSON.stringify(await contents(book)))throw Error('Contents changed after Niese');await history('goBack','niese-level',section);await niese(book,section);await history('goForward','contents-level');await contents(book);const url=page.url();await page.reload();await page.waitForFunction(()=>window.__combinedReady);if(page.url()!==url||JSON.stringify(c)!==JSON.stringify(await contents(book)))throw Error('Contents reload');
 const final=book===8?420:281;await open(`/antiquities/?book=${book}&niese=${final}&extra=keep#retained`);const last=await niese(book,final);await change('#chapter-selector','contents');await contents(book);await radio('#niese-level');await change('#niese-selector',String(final));if(JSON.stringify(last)!==JSON.stringify(await niese(book,final)))throw Error('Niese roundtrip');await page.reload();await page.waitForFunction(()=>window.__combinedReady);await niese(book,final);await history('goBack','niese-level',1);await history('goForward','niese-level',final);await niese(book,final);
 await change('#chapter-selector','1');if(new URL(page.url()).searchParams.has('niese')||new URL(page.url()).searchParams.has('view'))throw Error('Chapter conflicting URL');await radio('#subchapter-level');if(!new URL(page.url()).searchParams.has('subchapter'))throw Error('Subchapter transition');await radio('#section-level');if(!new URL(page.url()).searchParams.has('unit'))throw Error('Alignment transition');if(!await page.locator('#bamberg-level').isDisabled())throw Error('Bamberg VI-XI must remain unavailable');
 report.checks.push({book,width,theme,directions:['Contents-Niese-Contents','Niese-Contents-Niese'],reload:'PASS',history:'PASS',paneSwitching:'PASS',independentContents:'PASS',english:'broader aligned context',controls:'PASS',result:'PASS'});save();console.log('combined',book,width,theme);
}
for(const theme of ['light','dark']){
 await open('/antiquities/?book=8&view=contents');await page.evaluate(t=>setTheme(t),theme);for(const book of [9,10,8]){await change('#book-selector',String(book).padStart(2,'0'));await contents(book);if(await page.locator('#niese-level').isDisabled()!==(book===9))throw Error('Noncontiguous availability in contents');}
 await radio('#niese-level');await change('#book-selector','09');if(!await page.locator('#niese-level').isDisabled()||new URL(page.url()).searchParams.has('niese')||await page.locator('#chapter-selector').inputValue()==='contents')throw Error('IX stale Niese/contents');await snap('Antiquities-9-unsupported-Niese-'+theme);await change('#book-selector','10');await radio('#niese-level');await niese(10,1);
 await open('/antiquities/?book=9&niese=1');if(!await page.locator('#niese-level').isDisabled()||new URL(page.url()).searchParams.has('niese'))throw Error('Manual IX unsupported URL');
 report.checks.push({theme,bookSwitch:'VIII-IX-X',unsupportedIX:'PASS',directUnsupported:'PASS',result:'PASS'});
}
for(let book=1;book<=20;book++){await open(`/antiquities/?book=${book}`);const a=await page.evaluate(()=>({disabled:document.querySelector('#niese-level').disabled,identities:[...document.querySelector('#niese-selector').options].filter(o=>o.value).map(o=>Number(o.value))}));const supported=book<=8||book===10;if(a.disabled===supported||a.identities.length!==new Set(a.identities).size)throw Error('Coverage availability '+book);if(!supported&&a.identities.length)throw Error('Unsupported options '+book);report.availability.push({book,...a,result:'PASS'});}
report.verifiedSelections=report.availability.reduce((n,x)=>n+x.identities.length,0);if(report.verifiedSelections!==3157)throw Error('Actual total '+report.verifiedSelections);
for(const theme of ['light','dark'])for(const book of [3,20,14]){await open(`/antiquities/?book=${book}&view=contents`);await page.evaluate(t=>setTheme(t),theme);await page.waitForTimeout(550);await snap(`Contents-${book}-${theme}`);}
if(report.errors.length||report.consoleErrors.length||report.requests.length)throw Error('Browser exceptions/console/network failures');report.result='PASS';save();await browser.close();server.close();console.log('COMBINED_INTERACTION_PASS',report.checks.length,report.verifiedSelections);
})().catch(e=>{report.result='FAIL';report.failure=String(e);save();console.error(e);server.close();process.exit(1);});
